<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>

<section class="main-content">
    <div class="container">
        <div class="main-content__inner">
            <?php $this->getTemplateByFile('./templates/pages/parts/aside.phtml',[])?>
            <main class="main main-content__main">
                <div class="showcase">
                    <div class="showcase__content">
                        <div>
                            <h1 class="showcase__title showcase__title--business">Для бизнеса</h1>
                        </div>
                        <div class="showcase__number showcase__number--news" >
                            <?php $this->getTemplateByFile('./templates/pages/parts/svgs.phtml', ['what'=>'business'])?>
                        </div>
                    </div>
                </div>
                <div class="news news--offices">
                    <div class="">
                        <ul class="breadcrumbs news__breadcrumbs">
                            <li class="breadcrumbs__item">Главная  </li>
                            <li class="breadcrumbs__item">Для бизнеса</li>
                            <li class="breadcrumbs__item"><?=$this->getName($_RESPONSE['source'])?></li>
                        </ul>
                    </div>
                    <div class="info">
                        <h2 class="jobs__title jobs__title--business"><?=$this->getValue($_RESPONSE['source'], 'full_name')?></h2>
                        <h5 class="jobs__subtitle"><?=$this->getValue($_RESPONSE['source'], 'short_descr')?></h5>
                        <div class="jobs__info">
                            <?=$this->getValue($_RESPONSE['source'], 'full_descr', false)?>

                        </div>

                        <a href="#" class="jobs__info-btn">Отправить заявку</a>
                    </div>
                </div>
            </main>
        </div>
    </div>
</section>