<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>
<h2 class="page-header">Восстановление пароля</h2>

<?php if(isset($_RESPONSE['success'])):?>
    <div class="system-message-error"><?=$_RESPONSE['info']?></div>
<?php endif;?>
<?php if(!isset($_RESPONSE['success']) or (isset($_RESPONSE['success']) and !$_RESPONSE['success'])):?>
    <div id="action_reminder">
        <div class="login login-flat">
            <div class="login-container">
                <div class="loginFormWrap labeled">
                    <form method="POST">
                        <label>Ваша эл. почта:<input name="email" type="text"></label>
                        <input type="submit" value="Выслать ссылку на изменение пароля">
                    </form>
                </div>
            </div>
        </div>
    </div>
<?php endif;?>
