<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"/>
        <link rel="stylesheet" href="/css/reset.css">
        <link rel="stylesheet" href="/css/stardisk.css">

        <link rel="stylesheet" type="text/css" href="/css/slick.css"/>
        <link rel="stylesheet" type="text/css" href="/css/slick-theme.css"/>
        <link rel="stylesheet" href="/fonts/circe.fonts.css">
        <link rel="stylesheet" type="text/css" href="/css/select2.css"/>


        <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
        <link rel="stylesheet" href="/css/styles.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
        <style>
            table tr, table td {
                border: #000 solid 1px;
            }
        </style>

        <?php if(isset($_RESPONSE['page']) and $_RESPONSE['page']):?>
            <meta name="description" content="<?=$_RESPONSE['page']->getValue('meta_description')?>">
            <meta name="keywords" content="<?=$_RESPONSE['page']->getValue('meta_keywords')?>">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>
                <?php if($meta_title = $_RESPONSE['page']->getValue('meta_title')):?>
                    <?=$meta_title?>
                <?php else:?>
                    <?php if($pageName = $_RESPONSE['page']->getName()):?>
                        <?=$pageName?>
                    <?php else:?>
                        <?=$this->getSetting('site_name')?>
                    <?php endif;?>
                <?php endif;?>
            </title>
        <?php else:?>
            <title><?=$this->getSetting('site_name')?></title>
        <?php endif;?>
    </head>
    <body>
        <header class="header">
            <div class="header__modal-menu">
                <div class="container">
                    <div class="header__menu-inner">
                        <ul class="header__menu-list">
                            <?php $headerMenu = $this->macros('menu', 'getMenu', ['header_menu']);?>
                            <?php foreach($headerMenu as $menuItem):?>
                                <li class="header__menu-item">
                                    <a href="<?=$menuItem['href']?>" class="header__menu-link"><?=$menuItem['name']?></a>
                                </li>
                            <?php endforeach;?>
                        </ul>
                        <div class="header__menu-footer">
                            <div class="header__menu-social">
                                <h5 class="socials__title">Мы в социальных сетях</h5>
                                <ul class="socials__list">
                                    <?php $socials = $this->macros('guides', 'list_items', ['socials', false, true]);?>
                                    <?php foreach($socials['data'] as $socItem):?>
                                        <li class="socials__list-item">
                                            <a href="<?=$this->getValue($socItem, 'link')?>">
                                                <svg class="socials__img"><use xlink:href="/sprite.svg#<?=$this->getValue($socItem, 'svg_anchor')?>"></use></svg>
                                            </a>
                                        </li>
                                    <?php endforeach;?>
                                </ul>
                            </div>
                            <div class="header__menu-app">
                                <h5 class="socials__title">Мобильное приложение:</h5>
                                <ul class="socials__list">
                                    <?php $mobApps = $this->macros('guides', 'list_items', ['mobile_apps_list', false, true]);?>
                                    <?php foreach($mobApps['data'] as $mobAppLink):?>
                                        <li class="socials__list-item">
                                            <a href="<?=$this->getValue($mobAppLink, 'link')?>">
                                                <img class="socials__list-img" src="<?=$this->getValue($mobAppLink, 'btn_link')?>" alt="<?=$this->getName($mobAppLink)?>">
                                            </a>
                                        </li>
                                    <?php endforeach;?>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="header__top">
                <div class="container">
                    <div class="header__inner">
                        <div class="header__left">
                            <div class="header__burger">
                                <svg class="header__burger-svg header__burger-svg--bars"><use xlink:href="/sprite.svg#burger"></use></svg>
                                <svg class="header__burger-svg header__burger-svg--close"><use xlink:href="/sprite.svg#close"></use></svg>
                            </div>
                            <img class="header__logo" src="<?=$this->getSetting('logo')?>" alt="logo" />
                            <div class="header__phone"><?=$this->getSetting('phone_number')?><br><span class="header__work-time"><?=$this->getSetting('work_hours')?></span></div>
                        </div>
                        <nav class="navbar header__navbar">
                            <ul class="navbar__list">
                                <li class="navbar__item">
                                    <a href="/vacancy" class="navbar__link"><svg class="navbar__icon">
                                            <use xlink:href="/sprite.svg#vacance"></use></svg>
                                        <span class="navbar__text">Вакансии</span>
                                    </a>
                                </li>
                                <li class="navbar__item">
                                    <a href="/docs" class="navbar__link">
                                        <svg class="navbar__icon">
                                            <use xlink:href="/sprite.svg#doc"></use>
                                        </svg>
                                        <span class="navbar__text">Документы</span>
                                    </a>
                                </li>
                                <li class="navbar__item"><a href="/ask" class="navbar__link">
                                        <svg class="navbar__icon">
                                            <use xlink:href="/sprite.svg#question"></use>
                                        </svg>
                                        <span class="navbar__text">Задать вопрос</span>
                                    </a>
                                </li>
                                <li class="navbar__item navbar__item--search">
                                    <a href="/search" class="navbar__link" id="search-js">
                                        <svg class="navbar__icon">
                                            <use xlink:href="/sprite.svg#search"></use>
                                        </svg>
                                        <span class="navbar__text">Поиск</span>
                                    </a>
                                </li>
                                <li class="navbar__item navbar__item--user">
                                    <a href="/lk/view/private_information" class="navbar__link">
                                        <svg class="navbar__icon">
                                            <use xlink:href="/sprite.svg#user"></use>
                                        </svg>
                                        <span class="navbar__text">Личный кабинет</span>
                                    </a>
                                </li>
                                <li class="navbar__item navbar__item--profil">
                                    <a href="/lk/view/private_information" class="navbar__link">
                                        <img class="navbar__icon" src="/img/user-profil.svg" alt="">
                                        <span class="navbar__text navbar__text--profil">
                                            <span class="navbar__name">Иванов Иван</span>
                                            <span class="navbar__counter">2</span>
                                            <i class="fas fa-angle-down navbar__fas-icon"></i>
                                        </span>
                                    </a>
                                </li>
                            </ul>

                            <div class="user__list-item user__list-item--menu">
                                <div class="user__inner-info">
                                    <img src="/img/user.png" alt="" class="user__portrait">
                                    <!-- <h4 class="user__name">Иванов Иван Иванович</h4> -->
                                    <a href="reservation1.html" class="user__btn">Записаться на прием <span class="user__badge">1</span></a>
                                    <a href="annulation.html" class="user__btn">Отказаться  от приема<span class="user__badge user__badge--active">2</span></a>
                                    <a href="status.html" class="user__btn">Статус заявления<span class="user__badge">1</span></a>
                                    <a href="request.html" class="user__btn">Официальное обращение в МФЦ<span class="user__badge">1</span></a>
                                    <a href="annulation2.html" class="user__btn">Отозвать обращение<span class="user__badge">1</span></a>
                                    <a href="master.html" class="user__btn">Выезд специалиста<span class="user__badge user__badge--active">1</span></a>
                                    <a href="freemaster.html" class="user__btn">Бесплатный выезд специалиста<span class="user__badge">1</span></a>
                                    <a href="formdata.html" class="user__btn user__btn--fixed">Отзыв согласия на обработку персональных данных<span class="user__badge">1</span></a>
                                    <a href="user.html" class="user__btn user__btn--active">Личная информация<span class="user__badge">1</span></a>
                                </div>
                            </div>
                        </nav>

                    </div>
                </div>
            </div>
        </header>
        <div class="wrapper">

            <?php $this->getTemplate($this->module,$this->method,$_RESPONSE)?>

            <div class="fix-nav">
                <a href="" class="fix-nav__item">
                    <img src="/img/v1.png" alt="">
                </a>
                <a href="" class="fix-nav__item fix-nav__item--img">
                    <img src="/img/g1.png" alt="">
                </a>
                <a href="" class="fix-nav__item fix-nav__item--img">
                    <img src="/img/g2.png" alt="">
                </a>
                <a href="" class="fix-nav__item fix-nav__item--img">
                    <img src="/img/g3.png" alt="">
                </a>
                <a href="" class="fix-nav__item">
                    <img src="/img/v2.png" alt="">
                </a>
                <a href="" class="fix-nav__item">
                    <img src="/img/v3.png" alt="">
                </a>
                <a href="" class="fix-nav__item">
                    <img src="/img/v4.png" alt="">
                </a>
                <a href="" class="fix-nav__item">
                    <img src="/img/v5.png" alt="">
                </a>
            </div>
            <div class="chat">
                <button class="button">
                    <svg class="button__svg"><use xlink:href="/sprite.svg#chat"></use></svg>
                </button>
            </div>
        </div>

        <footer class="footer">
            <div class="container">
                <ul class="footer__inner">
                    <li class="footer__item">
                        <div><a class="sidebar__link-logo" href="/"><img class="sidebar__main-logo"  src="<?=$this->getSetting('mfc_logo')?>" alt=""></a></div>
                        <br/><br/>
                        <h4 class="footer__title">Мобильное приложение:</h4>
                        <?php foreach($mobApps['data'] as $mobAppLink):?>
                            <div>
                                <a href="<?=$this->getValue($mobAppLink, 'link')?>">
                                    <img src="<?=$this->getValue($mobAppLink, 'btn_link')?>" alt="<?=$this->getName($mobAppLink)?>">
                                </a>
                            </div><br>
                        <?php endforeach;?>
                    </li>
                    <li class="footer__item">
                        <h4 class="footer__title">Наши сервисы:</h4>
                        <ul class="footer__list">
                            <?php $footerMenu = $this->macros('menu', 'getMenu', ['footer_menu1']);?>
                            <?php foreach($footerMenu as $menuItem):?>
                                <li class="footer__list-item"><a href="<?=$menuItem['href']?>" class="footer__list-link"><?=$menuItem['name']?></a></li>
                            <?php endforeach;?>
                        </ul>
                    </li>
                    <li class="footer__item">
                        <h4 class="footer__title">Об МФЦ:</h4>
                        <ul class="footer__list">
                            <?php $footerMenu = $this->macros('menu', 'getMenu', ['footer_menu2']);?>
                            <?php foreach($footerMenu as $menuItem):?>
                                <li class="footer__list-item"><a href="<?=$menuItem['href']?>" class="footer__list-link"><?=$menuItem['name']?></a></li>
                            <?php endforeach;?>
                        </ul>
                    </li>
                    <li class="socials footer__item">
                        <div class="socials__inner">
                            <div class="socials__contact">
                                <p class="socials__phone"><?=$this->getSetting('phone_number')?></p>
                                <span class="socials__text"><?=$this->getSetting('work_hours')?></span>
                            </div>
                            <div class="socials__icons">
                                <h5 class="socials__title">Мы в социальных сетях</h5>
                                <ul class="socials__list">
                                    <?php foreach($socials['data'] as $socItem):?>
                                        <li class="socials__list-item">
                                            <a href="<?=$this->getValue($socItem, 'link')?>">
                                                <svg class="socials__img"><use xlink:href="/sprite.svg#<?=$this->getValue($socItem, 'svg_anchor')?>"></use></svg>
                                            </a>
                                        </li>
                                    <?php endforeach;?>
                                </ul>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </footer>

        <div class="modal" id="modal-js">
            <form class="modal__form" action="">
                <input class="modal__input" type="text" placeholder="Поиск">
                <button class="modal__btn" id="modal-btn-js" type="submit"><svg class="modal__svg-icon"><use xlink:href="/sprite.svg#icon-search"></use></svg></button>
                <h5 class="modal__form-title">Быстрые ответы:</h5>
                <ul class="modal__list">
                    <li class="modal__list-item">Офисы Екатеринбург</li>
                    <li class="modal__list-item">Документы для смены места жительства </li>
                    <li class="modal__list-item">Смена имени </li>
                    <li class="modal__list-item">Действия при утере документов</li>
                </ul>
            </form>
        </div>
        <section class="navbar-bottom">
            <ul class="navbar-bottom__list">
                <?php $mobBottomMenu = $this->macros('menu', 'getMenu', ['mobile_bottom_menu']);?>
                <?php foreach($mobBottomMenu as $menuItem):?>
                    <li class="navbar-bottom__item">
                        <a href="<?=$menuItem['href']?>" class="navbar-bottom__link">
                            <div class="navbar-bottom__picture">
                                <svg class="navbar-bottom__svg" style=" width:18px; height:18px;"><use xlink:href="/sprite.svg#<?=$menuItem['extend']?>"></use></svg>
                            </div>
                            <div class="navbar-bottom__text">
                            <span class="navbar-bottom__paragraph">
                                <?=$menuItem['name']?>
                            </span>
                            </div>
                        </a>
                    </li>
                <?php endforeach;?>
            </ul>
        </section>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
        <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
        <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
        <script src="/js/script.js"></script>
        <script>
            var site = {
                module: '<?=$this->module?>',
                method: '<?=$this->method?>',
                <?php if(router::$currentUser):?>
                user: {
                    type: '<?=router::$currentUser->getValue('type')?>',
                    id: <?=router::$currentUser->getId()?>
                }
                <?php endif;?>
            }
        </script>
        <script src="/js/stardisk.js"></script>
        <script src="/js/modules/<?= $this->module ?>.js?v=<?=time()?>"></script>
        <script src="/js/jquery.maskedinput.js"></script>
        <script src="/js/select2.js"></script>
        <script> $(function() { AOS.init(); }); </script>
    </body>
</html>