<?php if(isset($_RESPONSE['info'])):?>
    <?php if($_RESPONSE['success']):?>
        <div class="system-message-notice"><?=$_RESPONSE['info']?></div>
    <?php else:?>
        <div class="system-message-error"><?=$_RESPONSE['info']?></div>
    <?php endif;?>
<?php else:?>
    <?php if(isset($_RESPONSE['_tplFile'])):?>
        <div class="system-message-error">Отсутствует файл шаблона <?=$_RESPONSE['_tplFile']?>.</div>
    <?php endif;?>
<?php endif;?>

