<section class="main-content">
    <div class="container">
        <div class="main-content__inner">
            <?php $this->getTemplateByFile('./templates/pages/parts/aside.phtml',[])?>
            <main class="main main-content__main">
                <div class="showcase">
                    <div class="showcase__content">
                        <div>
                            <h1 class="showcase__title showcase__title--directories">О МФЦ</h1>
                        </div>
                        <div class="showcase__number showcase__number--jobs">
                            <?php $this->getTemplateByFile('./templates/pages/parts/svgs.phtml', ['what'=>'about'])?>
                        </div>
                    </div>
                </div>
                <div class="">
                    <div class="offers  offers--new">
                        <ul class="breadcrumbs offers__breadcrumbs offers__breadcrumbs--jobs">
                            <li class="breadcrumbs__item">Главная  </li>
                            <li class="breadcrumbs__item">О МФЦ</li>
                        </ul>
                    </div>
                    <div class="contacts page_about">
                        <div class="contacts__box">
                            <img class="contacts__box-img" src="<?=$this->macros('files','getFileURL',[$this->getValue($_RESPONSE['page'], 'about_about_mfc_image')])?>" alt="">
                            <h3 class="contacts__list-title">О МФЦ</h3>
                            <div class="contacts__description">
                                <?=$this->getValue($_RESPONSE['page'],'content', false)?>
                            </div>
                        </div>

                        <div class="contacts__box">
                            <img class="contacts__box-img" src="<?=$this->macros('files','getFileURL',[$this->getValue($_RESPONSE['page'], 'about_targets_img')])?>" alt="">
                            <h3 class="contacts__list-title">Цели и задачи</h3>
                            <div class="contacts__description targets_block">
                                <?=$this->getValue($_RESPONSE['page'],'about_targets', false)?>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
</section>