<section class="main-content">
    <div class="container">
        <div class="main-content__inner">
            <?php $this->getTemplateByFile('./templates/pages/parts/aside.phtml',[])?>
            <main class="main main-content__main">
                <div class="showcase">
                    <div class="showcase__content">
                        <div>
                            <h1 class="showcase__title showcase__title--directories">Контакты</h1>
                        </div>
                        <div class="showcase__number showcase__number--jobs">
                            <?php $this->getTemplateByFile('./templates/pages/parts/svgs.phtml', ['what'=>'contacts'])?>
                        </div>
                    </div>
                </div>
                <div class="">
                    <div class="offers  offers--new">
                        <ul class="breadcrumbs offers__breadcrumbs offers__breadcrumbs--jobs">
                            <li class="breadcrumbs__item">Главная  </li>
                            <li class="breadcrumbs__item">Контакты</li>
                        </ul>
                    </div>
                    <div class="contacts">
                        <div class="contacts__inner">
                            <div class="contacts__address">
                                <ul class="contacts__list">
                                    <li class="contacts__list-item">
                                        <h3 class="contacts__list-title">Адрес:</h3>
                                        <p class="contacts__list-text contacts__list-text--location address"><?=$this->getValue($_RESPONSE['page'], 'contacts_address')?></p>
                                    </li>
                                    <li class="contacts__list-item">
                                        <h3 class="contacts__list-title">Контакт-центр:</h3>
                                        <?php $phones = explode("\r\n", $this->getValue($_RESPONSE['page'],'contacts_phones'));?>
                                        <?php foreach($phones as $phone):?>
                                            <p class="contacts__list-text contacts__list-text--phone"><?=$phone?></p>
                                        <?php endforeach;?>
                                    </li>
                                    <li class="contacts__list-item">
                                        <h3 class="contacts__list-title">Размещение рекламы в МФЦ:</h3>
                                        <p class="contacts__list-text contacts__list-text--email"><?=$this->getValue($_RESPONSE['page'], 'contacts_ads')?></p>
                                    </li>
                                    <li class="contacts__list-item">
                                        <h3 class="contacts__list-title">Пресс-центр:</h3>
                                        <p class="contacts__list-text contacts__list-text--email"><?=$this->getValue($_RESPONSE['page'], 'contacts_press')?></p>
                                    </li>
                                    <li class="socials contacts__list-item">
                                        <h3 class="contacts__list-title">Мы в социальных сетях:</h3>
                                        <ul class="socials__list">
                                            <?php $socials = $this->macros('guides', 'list_items', ['socials', false, true]);?>
                                            <?php foreach($socials['data'] as $socItem):?>
                                                <li class="socials__list-item">
                                                    <a href="<?=$this->getValue($socItem, 'link')?>">
                                                        <svg class="socials__img"><use xlink:href="/sprite.svg#<?=$this->getValue($socItem, 'svg_anchor')?>"></use></svg>
                                                    </a>
                                                </li>
                                            <?php endforeach;?>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                            <?php $coords = $this->getValue($_RESPONSE['page'], 'contacts_map');?>
                            <div id="map-office" class="contacts__map" data-coords="<?=$coords?>"></div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
</section>