<section class="main-content">
<div class="container">
<div class="main-content__inner">
<?php $this->getTemplateByFile('./templates/pages/parts/aside.phtml',[])?>
<main class="main main-content__main">
    <div class="showcase">
        <div class="showcase__content">
            <div>
                <h1 class="showcase__title"  data-aos="fade-right"  data-aos-duration="1500">МНОГОФУНКЦИОНАЛЬНЫЙ<br/><span class="showcase__strong">ЦЕНТР СВЕРДЛОВСКОЙ ОБЛАСТИ</span></h1>
            </div>
            <div class="showcase__number"  data-aos="fade-left" data-aos-duration="1500">
                <div class="showcase__phone showcase__phone--showcase"><?=$this->getSetting('phone_number')?>
                    <span class="showcase__work-time showcase__work-time--showcase"><?=$this->getSetting('work_hours')?></span>
                </div>
                <a href="/lk/view/reservation" class="btn-animation">Онлайн-запись в МФЦ</a>
            </div>
        </div>

        <div class="banner-slider showcase__slider">
            <?php $slider = $this->getValue($_RESPONSE['page'], 'main_slider') ?>
            <?php if(is_array($slider)):?>
                <?php foreach($slider as $slide):?>
                    <div class="showcase__slider-item">
                        <?php if($slideImg = $this->getValue($slide, 'img')):?>
                            <img src="<?=$this->macros('files','preview',[$slideImg, 1193, 482, 'crop'])?>" alt="">
                        <?php else:?>
                            <img src="/img/banner_bg.png" alt="">
                        <?php endif;?>
                        <div class="showcase__slider-caption" style="<?=$this->getValue($this->getValue($slide, 'placing'), 'props')?>">
                            <h3 class="showcase__slider-title"><span class="showcase__slider-title-strong"><?=$this->getName($slide)?></span><br><?=$this->getValue($slide, 'sub_head')?></h3>
                            <p class="showcase__slider-text"><?=$this->getValue($slide, 'descr')?></p>
                        </div>
                    </div>
                <?php endforeach;?>
            <?php endif;?>
        </div>
    </div>



    <?php $sitData = $this->macros('services', 'getSituations', [])?>

    <ul class="services">
        <?php foreach($sitData['situations']['data'] as $situation):?>
            <li class="services__item">
                <a href="/our_services?sit=<?=$this->getId($situation)?>">
                    <div class="services__card aos-init aos-animate" data-aos="flip-left" data-aos-once="true" data-aos-duration="1500" data-aos-easing="linear">
                        <div class="services__wrap-img">
                            <img src="<?=$this->getValue($situation, 'img')?>" alt="" class="services__img">
                        </div>
                        <div class="services__overlay">
                            <h4 class="services__title"><?=$this->getName($situation)?></h4>
                            <div class="services__text">
                                <?php
                                    $sCount = (isset($sitData['counters'][$this->getId($situation)])) ? $sitData['counters'][$this->getId($situation)] : 0;
                                ?>
                                <span><?=$sCount?></span> <?=$this->declension($sCount, 'услуга', 'услуги', 'услуг')?>
                            </div>
                        </div>
                        <span class="services__left"></span>
                        <span class="services__right"></span>
                    </div>
                </a>
            </li>
        <?php endforeach;?>

        <li class="services__item">
            <a href="/services"></a>
            <div class="services__card aos-init aos-animate" data-aos="flip-left" data-aos-delay="50" data-aos-duration="1500" data-aos-easing="linear" data-aos-once="true">
                <div class="services__wrap-img">
                    <img src="/img/serv8.svg" alt="" class="services__img">
                </div>
                <div class="services__overlay">
                    <h4 class="services__title">Все услуги нашего МФЦ</h4>
                    <div class="services__text"><span><?=$sitData['totalServices']?></span> услуг</div>
                </div>
                <span class="services__left"></span>
                <span class="services__right"></span>
            </div>
        </li>
    </ul>
    <div class="news">

    </div>
</main>
</div>
</div>
</section>
<section class="main-content main-content--news">
    <div class="container">
        <div class="main-content__inner">
            <div class="sidebar main-content__sidebar">
                <p class="sidebar__paragraphe" >Соотношение заболевших в мире</p>
                <img class="sidebar__stat"
                     src="img/stat1.svg"
                     alt=""
                     data-aos="fade-right"
                     data-aos-delay="50"
                     data-aos-duration="800"
                     data-aos-once="true"
                     data-aos-easing="ease-in-sine"
                    >
                <ul class="sidebar__radio-list"
                    data-aos="flip-left"
                    data-aos-delay="50"
                    data-aos-duration="800"
                    data-aos-easing="ease-in-sine"
                    data-aos-once="true"
                    >
                    <li class="sidebar__radio-item">
                        <label class="sidebar__label"><input class="sidebar__radio" type="radio" name="radio"><span></span>  в Области</label>
                    </li>
                    <li class="sidebar__radio-item">
                        <label class="sidebar__label"><input class="sidebar__radio" type="radio" name="radio"><span></span>  В России</label>
                    </li>
                    <li class="sidebar__radio-item">
                        <label class="sidebar__label"><input class="sidebar__radio" type="radio" name="radio"><span></span>  В мире</label>
                    </li>
                </ul>
                <p class="sidebar__paragraphe"  >Соотношение заболевших в мире</p>
                <img src="img/stat2.svg" alt="" class="sidebar__stat"
                     data-aos="fade-up"
                     data-aos-delay="50"
                     data-aos-duration="800"
                     data-aos-once="true"
                     data-aos-easing="ease-in-sine"
                    >
                <ul class="sidebar__radio-list"
                    data-aos="flip-left"
                    data-aos-duration="800"
                    data-aos-easing="ease-in-sine"
                    data-aos-once="true"
                    >
                    <li class="sidebar__radio-item">
                        <label class="sidebar__label"><input class="sidebar__radio" type="radio" name="radio"><span></span>  В России</label>
                    </li>
                    <li class="sidebar__radio-item">
                        <label class="sidebar__label"><input class="sidebar__radio" type="radio" name="radio"><span></span>  В мире</label>
                    </li>
                </ul>
            </div>

            <?php $dataForMain = $this->macros('pages', 'dataForMainPage', []) ?>

            <div class="news main-content__main main-content__main--news">
                <div class="news__info" data-aos="fade-right" data-aos-duration="800" data-aos-easing="ease-in-sine" data-aos-once="true">
                    <h4 class="news__title">Новости</h4>
                    <div class="news__wrap-card">
                        <?php foreach($dataForMain['news']['data'] as $news):?>
                            <a href="/news/view/<?=$this->getId($news)?>" class="news__info-card clearfix">
                                <img src="<?=$this->macros('files','preview', [$this->getValue($news, 'img'), 386, 246, 'crop'])?>" alt="" class="news__info-image">
                                <div class="news__inner-cart">
                                    <p class="news__info-text"><?=$this->getName($news)?></p>
                                    <!-- <a href="#" class="news__info-btn">Подробнее</a> -->
                                </div>
                            </a>
                        <?php endforeach;?>
                    </div>
                    <div><a href="/news" class="news__slider-btn news__slider-btn--light hide-news-btn">Все новости</a></div>
                </div>
                <div class="news__content notices_wrp" data-aos="fade-up" data-aos-duration="800" data-aos-easing="ease-in-sine" data-aos-once="true">
                    <h4 class="news__title">Объявления</h4>
                    <ul class="news__card-list">
                        <?php foreach($dataForMain['notices']['data'] as $notice):?>
                            <a href="/notices/lists/?notice_id=<?=$this->getId($notice)?>" class="news__card-item">
                                <p class="news__card-text"><?=$this->getName($notice)?></p>
                                <div class="news__card-footer">
                                    <span class="news__card-date"><?=$this->formatDate($this->getValue($notice, 'create_time'))?></span>
                                    <!-- <span class="news__card-btn">Праздники</span> -->
                                </div>
                            </a>
                        <?php endforeach;?>
                    </ul>
                    <a href="/notices" class="news__content-btn news__slider-btn news__slider-btn--light">Все объявления</a>
                </div>
                <div class="news__slider" data-aos="fade-left" data-aos-delay="50" data-aos-duration="800" data-aos-easing="ease-in-sine" data-aos-once="true">
                    <h4 class="news__title">Истории</h4>
                    <div class="slider news__slider-inner" data-aos="fade-up">
                        <?php foreach($dataForMain['stories']['data'] as $story):?>
                            <div class="news__slider-item">
                                <img class="news__slider-img" src="<?=$this->macros('files','preview', [$this->getValue($story, 'img'), false, 600, 'resize'])?>" alt="">
                                <div class="news__slider-caption">
                                    <p class="news__slider-text"><?=$this->getName($story)?></p>
                                    <a href="/stories/view/<?=$this->getId($story)?>" class="news__slider-btn news__slider-btn--show">Подробнее</a>
                                </div>
                            </div>
                        <?php endforeach;?>
                    </div>
                    <a href="/stories" class="news__slider-btn news__slider-btn--light news__slider-btn--last">Все истории</a>
                </div>
            </div>
        </div>

    </div>
</section>
<section class="main-content main-content--info">
<div class="container">
<div class="main-content__inner">
<div class="sidebar main-content__sidebar">
    <img class="sidebar__pub-img" src="img/pub.png" alt="">
    <p class="sidebar__paragraphe">Средний возраст наших посетителей</p>
    <img src="img/stat3.svg" alt="" class="sidebar__stat-img">
    <ul class="sidebar__radio-list">
        <li class="sidebar__radio-item">
            <label class="sidebar__label"><input class="sidebar__radio" type="radio" name="radio"><span></span>  молодые</label>
        </li>
        <li class="sidebar__radio-item">
            <label class="sidebar__label"><input class="sidebar__radio" type="radio" name="radio"><span></span>  среднего возраста</label>
        </li>
        <li class="sidebar__radio-item">
            <label class="sidebar__label"><input class="sidebar__radio" type="radio" name="radio"><span></span>  пожилые</label>
        </li>
        <li class="sidebar__radio-item">
            <label class="sidebar__label"><input class="sidebar__radio" type="radio" name="radio"><span></span>  другие</label>
        </li>
    </ul>
</div>
<div class="info main-content__main main-content__main--info">
<h3 class="info__title">Полезные ресурсы</h3>
<?php $usefulRes = $this->macros('guides', 'list_items', ['useful_resources', false, true, false, false, true])?>
<ul class="partener-slider info__partener-list">
    <?php foreach($usefulRes['data'] as $item):?>
        <li class="info__partener-item">
            <div class="info__partener-inner">
                <a href="<?=$this->getValue($item, 'link')?>">
                    <div class="info__partener-wrap-img">
                        <img class="info__partener-img" src="<?=$this->getValue($item, 'img')?>" alt="">
                    </div>
                    <h5 class="info__partener-caption"><?=$this->getName($item)?></h5>
                </a>
            </div>
        </li>
    <?php endforeach;?>
</ul>
<h3 class="info__title">Наши офисы и центры</h3>
<form class="info__form">
    <span class="info__form-btn info__form-btn--active" id="onmap">На карте</span>
    <span class="info__form-btn" id="onlist">Списком</span>
    <div class="info__wrap-list">
        <div>
            <input class="info__form-input" id="office_search" type="text" placeholder="Начните вводить адрес...">
        </div>
        <div id="fullmap" class="info__yandex-map info__yandex-map--api"></div>
        <ul class="info__form-list" id="search_list" style="display: none">

        </ul>
    </div>

    <textarea id="allOfficeMapData" style="display: none"><?=json_encode($this->macros('offices','getAllOfficesCoords',[]))?></textarea>

    <?php $someOffices = $this->macros('offices', 'officeFilter', [12]) ?>
    <div class="info__list-offices" id="office_list">
        <?php foreach($someOffices['data'] as $office):?>
            <a href="/offices/view/<?=$this->getId($office)?>" class="info__form-list-item">
                <svg class="info__form-svg"><use xlink:href="/sprite.svg#loc"></use></svg>
                <span class="info__form-city"><?=$this->getName($office)?></span>
            </a>
        <?php endforeach;?>
    </div>
</form>
<h4 class="info__time-title">Выберите время ожидания:</h4>
<div>
    <label class="info__label" ><input class="info__radio" type="radio" name="radio"><span class="info__out info__out--first"></span>  менее 5 минут</label>
    <label class="info__label"><input class="info__radio" type="radio" name="radio"><span class="info__out info__out--second"></span>  от 15 до 30 минут</label>
</div>
<div>
    <label class="info__label"><input class="info__radio" type="radio" name="radio"><span class="info__out info__out--middle"></span>  более 30 минут</label>
    <label class="info__label"><input class="info__radio" type="radio" name="radio"><span class="info__out info__out--last"></span>  нет данных</label>
</div>
    <div class="info__map">
        <div id="tooltip">testing</div>
        <svg id="map-svg" width="564" height="681" viewBox="0 0 564 681" fill="none" xmlns="http://www.w3.org/2000/svg">
            <g clip-path="url(#clip0)">
                <?php $districts = $this->macros('guides', 'list_items', [31, false, true, false, false, true]);?>
                <?php foreach($districts['data'] as $district):?>
                    <?php
                        $svg = str_replace('<path ', '<path data-id="'.$this->getId($district).'"', $this->getValue($district, 'svg', false));
                    ?>
                    <?=$svg;?>
                <?php endforeach;?>
            </g>
            <defs>
                <clipPath id="clip0">
                    <rect width="564" height="681" fill="white"/>
                </clipPath>
            </defs>
        </svg>
    </div>
    <div id="map" class="info__yandex-map"></div>
</div>
</div>
</div>
</section>