<section class="main-content">
    <div class="container">
        <div class="main-content__inner">
            <?php $this->getTemplateByFile('./templates/pages/parts/aside.phtml',[])?>
            <main class="main main-content__main">
                <div class="showcase">
                    <div class="showcase__content">
                        <div>
                            <h1 class="showcase__title showcase__title--directories"><?=$this->getValue($_RESPONSE['page'],'name', false)?></h1>
                        </div>
                        <div class="showcase__number showcase__number--jobs">
                            <?php $this->getTemplateByFile('./templates/pages/parts/svgs.phtml', ['what'=>'about'])?>
                        </div>
                    </div>
                </div>
                <div class="">
                    <div class="offers  offers--new">
                        <ul class="breadcrumbs offers__breadcrumbs offers__breadcrumbs--jobs">
                            <li class="breadcrumbs__item">Главная  </li>
                            <li class="breadcrumbs__item"><?=$this->getValue($_RESPONSE['page'],'name', false)?></li>
                        </ul>
                    </div>
                  <div class="user">
                    <div class="user__inner"><?=$this->getValue($_RESPONSE['page'],'content', false)?></div>
                  </div>
                </div>
            </main>
        </div>
    </div>
</section>