<?php /** @var templater $this */ ?>
<?php /** @var array $_RESPONSE */ ?>
<section class="main-content">
    <div class="container">
        <div class="main-content__inner">
            <?php $this->getTemplateByFile('./templates/pages/parts/aside.phtml',[])?>
            <main class="main main-content__main">
                <div class="showcase">
                    <div class="showcase__content">
                        <div>
                            <h1 class="showcase__title showcase__title--services">Вакансии</h1>
                        </div>
                        <div class="showcase__number showcase__number--jobs">
                            <?php $this->getTemplateByFile('./templates/pages/parts/svgs.phtml', ['what'=>'vacancy'])?>
                        </div>
                    </div>
                </div>
                <div class="">
                    <div class="offers  offers--new">
                        <ul class="breadcrumbs offers__breadcrumbs offers__breadcrumbs--jobs">
                            <li class="breadcrumbs__item">Главная  </li>
                            <li class="breadcrumbs__item"> Вакансии</li>
                        </ul>
                    </div>
                    <div class="jobs">
                        <div class="jobs__banner">
                            <img src="/img/job-banner.png" alt="" class="jobs__banner-img">
                        </div>
                        <ul class="jobs__list">
                            <li class="jobs__list-item">
                                <div class="jobs__list-picture">
                                    <img src="/img/job1.png" alt="" class="jobs__list-img">
                                </div>
                                <div class="jobs__list-description">Работа рядом с домом</div>
                            </li>
                            <li class="jobs__list-item">
                                <div class="jobs__list-picture">
                                    <img src="/img/job2.png" alt="" class="jobs__list-img">
                                </div>
                                <div class="jobs__list-description">Официальное трудоустройство</div>
                            </li>
                            <li class="jobs__list-item">
                                <div class="jobs__list-picture">
                                    <img src="/img/job3.png" alt="" class="jobs__list-img">
                                </div>
                                <div class="jobs__list-description">Удобный график работы</div>
                            </li>
                            <li class="jobs__list-item">
                                <div class="jobs__list-picture">
                                    <img src="/img/job4.png" alt="" class="jobs__list-img">
                                </div>
                                <div class="jobs__list-description">Регулярное корпоративное обучение</div>
                            </li>
                            <li class="jobs__list-item">
                                <div class="jobs__list-picture">
                                    <img src="/img/job5.png" alt="" class="jobs__list-img">
                                </div>
                                <div class="jobs__list-description">Конкурентная заработная плата и социальные гарантии</div>
                            </li>
                            <li class="jobs__list-item">
                                <div class="jobs__list-picture">
                                    <img src="/img/job6.png" alt="" class="jobs__list-img">
                                </div>
                                <div class="jobs__list-description">Возможность карьерного роста</div>
                            </li>
                        </ul>

                        <div class="jobs__info">
                            <?=$this->getValue($_RESPONSE['page'], 'content', false);?>
                        </div>

                        <?php $vacancies = (isset($_RESPONSE['data'])) ? $_RESPONSE['data'] : $this->macros('vacancies','lists',[]);?>

                        <div class="our-services__filter our-services__filter--jobs">
                            <span class="our-services__name">Сортировать:<i class="fas fa-angle-down our-services__sort-icon"></i></span>
                            <ul class="our-services__filter-list">
                                <li class="our-services__filter-item our-services__filter-item--jobs">по району<i class="fas fa-angle-down our-services__fas-icon"></i></li>
                            </ul>
                        </div>
                        <ul class="jobs__card-list">
                            <?php foreach($vacancies['data'] as $vacancy):?>
                                <li class="jobs__card-item">
                                    <a href="/vacancies/view/<?=$this->getId($vacancy)?>">
                                        <h5 class="jobs__card-title"><?=$this->getName($vacancy)?></h5>
                                        <span class="jobs__card-price">от <?=$this->getValue($vacancy, 'salary')?> рублей</span>
                                        <p class="jobs__card-description"><span class="jobs__card-strong">График:</span><?=$this->getValue($vacancy, 'schedule')?></p>
                                        <p class="jobs__card-description"><span class="jobs__card-strong">Требования:</span>
                                            <?php
                                                $requirements = explode("\r\n", $this->getValue($vacancy, 'requirements'));
                                                $reqTotal = count($requirements)-1;
                                                foreach ($requirements as $i=>$req){
                                                    echo $req;
                                                    if($i < $reqTotal){ echo ', ';}
                                                }
                                            ?>
                                        </p>
                                        <span class="jobs__card-date">Дата публикации: <?=$this->formatDate($this->getValue($vacancy, 'pub_date'))?></span>
                                    </a>
                                </li>
                            <?php endforeach;?>
                        </ul>
                    </div>
                </div>
            </main>
        </div>
    </div>
</section>