<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>

<section class="main-content">
    <div class="container">
        <div class="main-content__inner">
            <?php $this->getTemplateByFile('./templates/pages/parts/aside.phtml',[])?>
            <main class="main main-content__main">
                <div class="showcase">
                    <div class="showcase__content">
                        <div>
                            <h1 class="showcase__title showcase__title--services">Вакансии</h1>
                        </div>
                        <div class="showcase__number showcase__number--jobs">
                            <?php $this->getTemplateByFile('./templates/pages/parts/svgs.phtml', ['what'=>'vacancy'])?>
                        </div>
                    </div>
                </div>
                <div class="">
                    <div class="offers  offers--new">
                        <ul class="breadcrumbs offers__breadcrumbs offers__breadcrumbs--jobs">
                            <li class="breadcrumbs__item">Главная  </li>
                            <li class="breadcrumbs__item">Вакансии</li>
                            <li class="breadcrumbs__item">Вакансия <?=$this->getName($_RESPONSE['source'])?></li>
                        </ul>
                    </div>
                    <div class="jobs">
                        <h2 class="jobs__title">Старший делопроизводитель <span class="jobs__title-price">от <?=$this->getValue($_RESPONSE['source'], 'salary')?> рублей</span></h2>
                        <div class="jobs__description">
                            <img src="/img/job.png" alt="" class="jobs__description-img">
                            <div class="jobs__info jobs__info--job">
                                <h5 class="jobs__info-title jobs__info-title--main">Описание вакансии:</h5>
                                <p class="jobs__info-text jobs__info-text--job"><?=$this->getValue($_RESPONSE['source'], 'descr')?></p>
                            </div>
                        </div>
                        <div class="jobs__info">
                            <h5 class="jobs__info-title jobs__info-title--job">Обязанности:</h5>
                            <?=$this->getValue($_RESPONSE['source'], 'duties', false)?>
                        </div>
                        <div class="jobs__info">
                            <h5 class="jobs__info-title jobs__info-title--job">Требования:</h5>
                            <ul class="jobs__require-list">
                                <?php
                                $requirements = explode("\r\n", $this->getValue($_RESPONSE['source'], 'requirements'));
                                $reqTotal = count($requirements)-1;
                                foreach ($requirements as $i=>$req){
                                    echo '<li class="jobs__require-item">',$req,'</li>';
                                }
                                ?>
                            </ul>
                        </div>
                        <ul class="jobs__list jobs__list--job">
                            <li class="jobs__list-item jobs__list-item--job">
                                <div class="jobs__list-picture">
                                    <img src="/img/j1.png" alt="" class="jobs__list-img">
                                </div>
                                <div class="jobs__list-description">Работа рядом с домом</div>
                            </li>
                            <li class="jobs__list-item jobs__list-item--job">
                                <div class="jobs__list-picture">
                                    <img src="/img/j2.png" alt="" class="jobs__list-img">
                                </div>
                                <div class="jobs__list-description">Официальное трудоустройство</div>
                            </li>
                            <li class="jobs__list-item jobs__list-item--job">
                                <div class="jobs__list-picture">
                                    <img src="/img/j3.png" alt="" class="jobs__list-img">
                                </div>
                                <div class="jobs__list-description">Удобный график работы</div>
                            </li>
                            <li class="jobs__list-item jobs__list-item--job">
                                <div class="jobs__list-picture">
                                    <img src="/img/j4.png" alt="" class="jobs__list-img">
                                </div>
                                <div class="jobs__list-description">Регулярное корпоративное обучение</div>
                            </li>
                            <li class="jobs__list-item jobs__list-item--job">
                                <div class="jobs__list-picture">
                                    <img src="/img/j5.png" alt="" class="jobs__list-img">
                                </div>
                                <div class="jobs__list-description">Конкурентная заработная плата и социальные гарантии</div>
                            </li>
                            <li class="jobs__list-item jobs__list-item--job">
                                <div class="jobs__list-picture">
                                    <img src="/img/j6.png" alt="" class="jobs__list-img">
                                </div>
                                <div class="jobs__list-description">Возможность карьерного роста</div>
                            </li>
                        </ul>

                        <?php $webform = $this->macros('webforms', 'getForm', [3]) ?>

                        <div class="jobs__mail">
                            <div>
                                <h6 class="jobs__mail-title">Остались вопросы?</h6>
                                <p class="jobs__mail-text">Свяжитесь с нашим специалистом отдела кадров  по адресу:<span class="jobs__mail-strong"><?=$webform['email']?></span> </p>
                            </div>
                            <a href="mailto:<?=$webform['email']?>" class="jobs__mail-btn"><img class="jobs__mail-icon" src="/img/mail.png" alt=""><span>Написать</span></a>
                        </div>
                        <div class="jobs__publish">
                            <a href="#" class="main-btn jobs__publish-btn">Откликнуться</a>
                            <span class="jobs__publish-date">Дата публикации: <?=$this->formatDate($this->getValue($_RESPONSE['source'], 'pub_date'))?></span>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
</section>

<?php $this->getTemplateByFile('./templates/webforms/leave_apply.phtml', ['form'=>$webform, 'title'=>'Откликнуться на вакансию', 'btn_name'=>'Откликнуться']);