<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>

<div class="main_content_container">
    <h1>Добавить форму обратной связи</h1>
    <form action="/admin/webforms/add/" method="POST" id="form">
        <div class="main_content_container_wrap">
            <div class="row row_form">
                <div class="col-3">
                    <p class="form_label">Название вебформы</p>
                </div>
                <div class="col-9">
                    <div class="form_wrapper">
                        <input class="form_input" required="" type="text" name="descr" id="name" value="">
                    </div>
                </div>
            </div>

            <div class="row row_form">
                <div class="col-3">
                    <p class="form_label">Email для отправки</p>
                </div>
                <div class="col-9">
                    <div class="form_wrapper">
                        <input class="form_input" required="" type="text" name="email" id="email" value="">
                    </div>
                </div>
            </div>

            <hr>
            <h2>Поля формы</h2>
            <hr>
            <div id="fields">
                <div class="fieldWrp" style="margin-bottom: 20px" data-count="%id%">
                    <div class="row">
                        <div class="col-3">
                            <p class="form_label">Название поля</p>
                            <small>Системное название, может содержать только английские буквы и цифры</small>
                        </div>
                        <div class="col-3">
                            <div class="form_wrapper">
                                <input class="form_input" required="" type="text" name="field_name[%id%]" id="field_name" value="">
                            </div>
                        </div>
                        <div class="col-3">
                            <p class="form_label">Описание поля</p>
                        </div>
                        <div class="col-3">
                            <div class="form_wrapper">
                                <input class="form_input" required="" type="text" name="field_descr[%id%]" value="">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-3">
                            <p class="form_label">Тип поля</p>
                        </div>
                        <div class="col-3">
                            <div class="form_wrapper">
                                <select name="field_type[%id%]" required="">
                                    <option value="varchar">Строка</option>
                                    <option value="text">Текст</option>
                                    <option value="date">Дата</option>
                                    <option value="datetime">Дата и время</option>
                                    <option value="int">Число</option>
                                    <option value="float">Число с точкой</option>
                                    <option value="boolean">Галочка</option>
                                    <option value="file">Файл</option>
                                    <option value="list">Список определенных значений</option>
                                </select>
                            </div>
                        </div>

                        <div class="col-3 selectListItems" style="display: none">
                            <p class="form_label">Заполнить список</p>
                        </div>
                        <div class="col-3 selectListItems" style="display: none;">
                            <p class="listItemWrp">
                                <input type="text" name="field_values[%id%][]" placeholder="введите значение">
                                <a href="#" class="delListItem">[удалить]</a>
                            </p>
                            <a class="btn_sky addAnotherListItem" href="#">Добавить еще значение</a>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-3">
                            <p class="form_label">Приоритет вывода</p>
                            <small>Порядок, в котором поле будет отображаться в форме</small>
                        </div>
                        <div class="col-3">
                            <div class="form_wrapper">
                                <input class="form_input" type="number" name="field_index[%id%]" value="0">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-3">
                            <p class="form_label">Отображать в таблице</p>
                            <small>Значение поля будет отображаться в таблице элементов</small>
                        </div>
                        <div class="col-3">
                            <div class="form_wrapper">
                                <input class="form_input" type="checkbox" name="field_table[%id%]" value="1">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-3">
                            <p class="form_label">Поле обязательно для заполнения</p>
                        </div>
                        <div class="col-3">
                            <div class="form_wrapper">
                                <input class="form_input" type="checkbox" name="field_required[%id%]" value="1">
                            </div>
                        </div>
                    </div>

                    <a href="#" class="delField btn_sky">Удалить</a>
                    <hr>
                </div>
            </div>

            <a href="#" class="btn_sky" id="addfield">Добавить поле</a>
        </div>

        <div class="form_buttons">
            <div class="row">
                <div class="col-auto">
                    <button class="btn btn-success">Сохранить</button>
                </div>
            </div>
        </div>
    </form>
</div>