<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Список форм обратной связи</h1><a href="/admin/webforms/add" class="btn btn-outline-dark"><span data-feather="plus-circle"></span> Добавить форму</a>
</div>
<table class="table table-striped table-sm numered">
    <thead>
    <tr>
        <th>ID</th>
        <th>Название</th>
        <th>Просмотреть записи</th>
    </tr>
    </thead>
    <tbody>
    <?php if($_RESPONSE):?>
        <?php foreach($_RESPONSE['data'] as $webform):?>
            <tr>
                <td>
                    <?=$webform->getId()?>
                </td>
                <td>
                    <a href="/admin/webforms/edit/<?=$webform->getId()?>"><?=$webform->getName()?></a>
                </td>
                <td>
                    <a href="/admin/guides/list_items/<?=$webform->getValue('guide_id')?>">Просмотреть записи</a>
                </td>
            </tr>
        <?php endforeach;?>
    <?php else:?>
        <tr>
            <td class="table_no_resources" colspan="6">
                <p>Нет данных для отображения</p>
            </td>
        </tr>
    <?php endif;?>
    </tbody>
</table>


<div class="lists_table_footer">
    <div class="row">
        <div class="col-4">

        </div>
        <div class="col-8">
            <!-- --><?php /*$this->getTemplate('search','numpages',array('total'=>$_RESPONSE['total']))*/?>
        </div>
    </div>
</div>
