<section class="main-content">
    <div class="container">
        <div class="main-content__inner">
            <?php $this->getTemplateByFile('./templates/pages/parts/aside.phtml',[])?>
            <main class="main main-content__main">
                <div class="showcase">
                    <div class="showcase__content">
                        <div>
                            <h1 class="showcase__title showcase__title--services">Истории</h1>
                        </div>
                        <div class="showcase__number showcase__number--news">
                            <?php $this->getTemplateByFile('./templates/pages/parts/svgs.phtml', ['what'=>'stories'])?>
                        </div>
                    </div>
                </div>
                <div class="stories">
                    <div class="news">
                        <ul class="breadcrumbs news__breadcrumbs">
                            <li class="breadcrumbs__item">Главная  </li>
                            <li class="breadcrumbs__item">Истории</li>
                        </ul>
                    </div>
                    <?php $tags = $this->macros('guides', 'list_items', ['stories_tags', false, false, false, false, true]);?>
                    <div class="news__top-nav clearfix">
                        <?php foreach($tags['data'] as $tag):?>
                            <a href="?tag=<?=$this->getId($tag)?>" class="news__top-navlink"><?=$this->getName($tag)?></a>
                        <?php endforeach;?>
                    </div>

                    <?php $stories = $this->macros('stories', 'lists', [false, true]) ?>

                    <ul class="stories__list">
                        <?php foreach($stories['data'] as $story):?>
                            <li class="stories__item">
                                <div class="stories__card">
                                    <img class="stories__card-img" src="<?=$this->macros('files','getFileURL', [$this->getValue($story, 'img')])?>" alt="">
                                    <div class="stories__card-text"><?=$this->getName($story)?></div>
                                    <a href="/stories/view/<?=$this->getId($story)?>" class="stories__card-btn">Подробнее</a>
                                </div>
                            </li>
                        <?php endforeach;?>
                    </ul>
                    <?php $this->getTemplateByFile('./templates/pages/parts/numpages.phtml', ['total'=>$stories['total']])?>


                </div>
            </main>
        </div>
    </div>
</section>