<section class="main-content">
    <div class="container">
        <div class="main-content__inner">
            <?php $this->getTemplateByFile('./templates/pages/parts/aside.phtml',[])?>
            <main class="main main-content__main">
                <div class="showcase">
                    <div class="showcase__content">

                        <div>
                            <h1 class="showcase__title showcase__title--services">Истории</h1>
                        </div>
                        <div class="showcase__number showcase__number--news">
                            <?php $this->getTemplateByFile('./templates/pages/parts/svgs.phtml', ['what'=>'stories'])?>
                        </div>
                    </div>
                </div>
                <div class="">
                    <div class="offers">
                        <ul class="breadcrumbs offers__breadcrumbs">
                            <li class="breadcrumbs__item">Главная  </li>
                            <li class="breadcrumbs__item">Истории</li>
                            <li class="breadcrumbs__item"> <?=$this->getName($_RESPONSE['source'])?></li>
                        </ul>
                        <h2 class="offers__title"><?=$this->getName($_RESPONSE['source'])?></h2>
                        <div class="offers__inner-btn">
                            <span class="offers__date"><?=$this->formatDate($this->getValue($_RESPONSE['source'], 'create_time'))?></span>
                            <?php if($tag = $this->getValue($_RESPONSE['source'], 'tag')):?>
                                <a href="/stories?tag=<?=$this->getId($tag)?>" class="offers__top-btn"><?=$this->getName($tag)?></a>
                            <?php endif;?>
                        </div>
                        <div class="new-blog">
                            <div class="new-blog__storie-slider">
                                <div class="newslider">
                                    <?php foreach($this->getValue($_RESPONSE['source'], 'more_photos') as $imgId):?>
                                        <div><img src="<?=$this->macros('files','preview', [$imgId, 445, 791, 'crop'])?>" /></div>
                                    <?php endforeach;?>
                                  </div>
                            </div>
                            <p class="new-blog__text"><?=$this->getValue($_RESPONSE['source'], 'content', false, false)?></p>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
</section>