
<?php $fields = $this->getValue($_RESPONSE['form'], 'groups_fields'); ?>

  <? 
        $groups = [];
        foreach($fields as $field){
            $groups[$field->getValue('section')][] = $field;
        }

        ksort($groups);
      
       
        $groups_count = count($groups);

        if ($this->getId($_RESPONSE['form'])==7){
          $groups_count++;
        }
  ?>
<? if ($groups_count>1){?>
<ul class="user__list-number">
  <? for ($i=1; $i<=$groups_count; $i++) {?>
    <li class="user__item-number <?=($i==1?'user__item-number--success':'')?>"><?=$i?></li>
  <?}?>
</ul>
<?}?>
<form action="" class="user__inner-form" id="form_gen" method="post">
    <!-- level-1 -->
  
  <?php 
    $row_size = 6;
    $level=1;
    foreach($groups as $groupId=>$fields):?>
    <div class="<?=($groups_count>1?'user__form-level ':'')?><?=($level==1?'level-js':'')?>">
      <? $fields_count = count($fields); $fields_counter = 0;?>
      <?php foreach($fields as $field):?>
      <? $field_type = $this->getValue($field, 'type', false, true);
         switch($this->getValue($field, 'width', false, true)){
           case 2: $field_size=3; break;
           case 3: $field_size=2; break;
           default: $field_size=6;
         }
        $fields_counter++;
        
        if ($row_size==6){
          echo '<div class="user__wrap-form-item">';
        }
      
        $row_size-=$field_size; 
        if ($row_size<0){
          echo '</div><div class="user__wrap-form-item">';
         
        }
        if($fields_count==$fields_counter) $row_size=0;
        
       $css_filter = '';
       if($field_type=='varcharru') $css_filter = 'input_cyr';
       if($field_type=='passport') $css_filter = 'input_pass';
       if($field_type=='email') $css_filter = 'input_mail';
       if($field_type=='phonenumber') $css_filter = 'input_phone';
       if($field_type=='snils') $css_filter = 'input_snils';
       if($field_type=='date') $css_filter = 'input_date';
      
      
        echo '<div class="user__form-item user__form-item--wrap user__form-item--fluid">';
        switch ($field_type){
          case 'boolean':
      ?>
          <label class="user__inner-text user__inner-text--input" for="input-agree"><input id="input-agree" class="<?=($this->getValue($field, 'required', false, true))?'f_required':''?>" type="checkbox" value="1">&nbsp; Я согласен с условиями <span style="font-weight: 700; text-decoration: underline;">публичной оферты</span></label>
      <?  break;
          case 'varchar':
          case 'varcharru':
          case 'snils':
          case 'phonenumber':
          case 'passport':
          case 'date':
          case 'datetime':
          case 'int':
          case 'float':
          case 'list':
          
      ?>
          <label class="user__form-label" for=""><?=$this->getValue($field, 'name', false, true)?> <?=($this->getValue($field, 'required', false, true))?'<span style="color: red">*</span>':''?></label>
          <div><input class="user__form-input <?=$css_filter;?>  <?=($this->getValue($field, 'required', false, true))?'f_required':''?>" name="field[<?=$this->getId($field)?>]" type="text" placeholder="" value="<?=(isset($_GET['lorem'])?$this->getValue($field, 'name', false, true):'')?>" ></div>

      <?
          break;
          case 'email':
          
      ?>
          <label class="user__form-label" for=""><?=$this->getValue($field, 'name', false, true)?> <?=($this->getValue($field, 'required', false, true))?'<span style="color: red">*</span>':''?></label>
          <div><input class="user__form-input <?=$css_filter;?>  <?=($this->getValue($field, 'required', false, true))?'f_required':''?>" name="field[<?=$this->getId($field)?>]" type="email" placeholder="" value="<?=(isset($_GET['lorem'])?$this->getValue($field, 'name', false, true):'')?>" ></div>

      <?
          break;
          case 'textarea':
          
      ?>
          <label class="user__form-label" for=""><?=$this->getValue($field, 'name', false, true)?> <?=($this->getValue($field, 'required', false, true))?'<span style="color: red">*</span>':''?></label>
          <div><textarea class="search__form-input <?=$css_filter;?>  <?=($this->getValue($field, 'required', false, true))?'f_required':''?>" name="field[<?=$this->getId($field)?>]" id="text-area" cols="30" rows="10" style="width: 100%;"><?=(isset($_GET['lorem'])?$this->getValue($field, 'name', false, true):'')?></textarea></div>

      <?
          break;
          case 'module_time_reservation':
      ?>
      <div class="calend_div">
                                                    <p class="modal__card-span" >Количество (пакетов документов, человек, услуг, объектов)</p>
                                                    <div class="calender">
                                                        <div class="calender__list docs_count_list">
                                                          <? for($i=1; $i<=15;$i++){?>
                                                          <button class="calender__list-item <?=($i==1?'calender__list-item--active':'')?>" onclick="docs_count_set(this,<?=$i?>); return false;"><?=$i?></button>
                                                          <?}?>
                                                            
                                                        </div>
                                                        <div class="calender__inner">
                                                            <div class="calender__inner-item">
                                                                <div class="light">
                                                                    <div class="calendar">
                                                                        <div class="calendar-header">
                                                                            
                                                                            <div class="year-picker">
                                                                                <span class="year-change" id="prev-year">
                                                                                    <pre>&lt;</pre>
                                                                                </span>
                                                                               <div>
                                                                                    <span class="month-picker" id="month-picker">Июль</span>
                                                                                    <span id="year">2021</span>
                                                                               </div>
                                                                                <span class="year-change" id="next-year">
                                                                                    <pre>&gt;</pre>
                                                                                </span>
                                                                            </div>
                                                                        </div>
                                                                        <div class="calendar-body">
                                                                            <div class="calendar-week-day">
                                                                                
                                                                                <div>Пн</div>
                                                                                <div>Вт</div>
                                                                                <div>Ср</div>
                                                                                <div>Чт</div>
                                                                                <div>Пт</div>
                                                                                <div>Сб</div>
                                                                                <div>Вс</div>
                                                                            </div>
                                                                            <div class="calendar-days"><div></div><div></div><div></div><div class="calendar-day-hover">1<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">2<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">3<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">4<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">5<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">6<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">7<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">8<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">9<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">10<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">11<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">12<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">13<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">14<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">15<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">16<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">17<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">18<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">19<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">20<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">21<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">22<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">23<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">24<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">25<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">26<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover curr-date">27<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">28<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">29<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">30<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div><div class="calendar-day-hover">31<span></span>
                            <span></span>
                            <span></span>
                            <span></span></div></div>
                                                                        </div>
                                                                        <div class="month-list"><div><div data-month="0">Январь</div></div><div><div data-month="1">Февраль</div></div><div><div data-month="2">Март</div></div><div><div data-month="3">Апрель</div></div><div><div data-month="4">Май</div></div><div><div data-month="5">Июнь</div></div><div><div data-month="6">Июль</div></div><div><div data-month="7">Август</div></div><div><div data-month="8">Сентябрь</div></div><div><div data-month="9">Октябрь</div></div><div><div data-month="10">Ноябрь</div></div><div><div data-month="11">Декабрь</div></div></div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="calender__inner-item">
                                                                <div class="calender__list calender__list--time">
                                                                    
                                                                </div>
                                                            </div>
                                                        </div> 
                                                    </div>
                                                    <input type="hidden" id="calend_date" class="f_required" value="" name="field[<?=$this->getId($field)?>]">
                                                    <!-- <span class="modal__card-close modal__card-close--calender" id="modal-close-calender-js"><i class="fas fa-times"></i></span> -->
                                                </div>
      <?
          break;
          case 'file':
        ?>
                                                <label class="user__form-label" for=""><?=$this->getValue($field, 'name', false, true)?> <?=($this->getValue($field, 'required', false, true))?'<span style="color: red">*</span>':''?></label>
                                                <div class="user__wrap-form-item user__wrap-form-item--btn">
                                                    <input class="user__form-input <?=($this->getValue($field, 'required', false, true))?'f_required':''?>" type="text" disabled id="file_upload_str">
                                                    <button class="user__inner-btn user__inner-btn--form user__inner-btn--m16" id="file_upload_btn">Загрузить</button>
                                                    <input type="file" name="field[<?=$this->getId($field)?>]" id="file_upload_input" style="display:none;">
                                                    <input type="hidden" name="photo[<?=$this->getId($field)?>]" id="webcam_upload_input" style="display:none;">
                                                  
                                                    <button class="user__inner-btn user__inner-btn--form" id="webcam-js">
                                                        <svg width="23" height="21" viewBox="0 0 23 21" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                            <path d="M21 5H17.83L16 3H9V5H15.12L16.95 7H21V19H5V9H3V19C3 20.1 3.9 21 5 21H21C22.1 21 23 20.1 23 19V7C23 5.9 22.1 5 21 5ZM8 13C8 15.76 10.24 18 13 18C15.76 18 18 15.76 18 13C18 10.24 15.76 8 13 8C10.24 8 8 10.24 8 13ZM13 10C14.65 10 16 11.35 16 13C16 14.65 14.65 16 13 16C11.35 16 10 14.65 10 13C10 11.35 11.35 10 13 10ZM5 8V5H8V3H5V0H3V3H0V5H3V8H5Z" fill="#E04E39"></path>
                                                        </svg>   
                                                    </button>
                                                  
                                                   <input class="user__form-input" type="hidden" id="file_upload">
                                                </div>
        <?
          break;
          case 'guide':
            $extra_id = $this->getValue($field, 'extra', false, true);
            if (($extra_id>0)){
              $guidelist = guides::list_items($extra_id,array(),1,'ASC','id',true);
             
        ?>
       <label class="user__form-label" for=""><?=$this->getValue($field, 'name', false, true)?> <?=($this->getValue($field, 'required', false, true))?'<span style="color: red">*</span>':''?></label>
              <div class="user__form-select">
                  <i class="fas fa-angle-down user__fas-icon"></i>
                  <select class="user__form-input user__form-input--select <?=($this->getValue($field, 'required', false, true))?'f_required':''?>" data-id="<?=$this->getId($field)?>" name="field[<?=$this->getId($field)?>]" >
                    <option value="">&nbsp;</option>
                    <? foreach($guidelist['data'] as $k=>$guide_item){?>
                    <option <?=(isset($_GET['lorem'])&&$k==0?'selected':'')?> value="<?=$guide_item->getId()?>" ><?=$guide_item->getValue('name')?></option>
                    <?}?>
                     
                  </select>
              </div>
      <?  }
          break;
            case 'guide_ajax':
            $extra_id = $this->getValue($field, 'extra', false, true);
            if (($extra_id>0)){
              $guidelist = guides::list_items($extra_id,array(),1,'ASC','id',true);
             
        ?>
       <label class="user__form-label" for=""><?=$this->getValue($field, 'name', false, true)?> <?=($this->getValue($field, 'required', false, true))?'<span style="color: red">*</span>':''?></label>
              <div class="user__form-select">
                  <i class="fas fa-angle-down user__fas-icon"></i>
                  <select class="user__form-input select2 user__form-input--select <?=($this->getValue($field, 'required', false, true))?'f_required':''?>" data-id="<?=$this->getId($field)?>" name="field[<?=$this->getId($field)?>]" >
                    <option value="">&nbsp;</option>
                    <? foreach($guidelist['data'] as $k=>$guide_item){?>
                    <option <?=(isset($_GET['lorem'])&&$k==0?'selected':'')?> value="<?=$guide_item->getId()?>" data-extra="<?=$guide_item->getValue('municipal_id')?>"><?=$guide_item->getValue('name')?></option>
                    <?}?>
                     
                  </select>
              </div>
      <?  }
          break;
          case 'guide_ajax_empty':
           
        ?>
       <label class="user__form-label" for=""><?=$this->getValue($field, 'name', false, true)?> <?=($this->getValue($field, 'required', false, true))?'<span style="color: red">*</span>':''?></label>
              <div class="user__form-select">
                  <i class="fas fa-angle-down user__fas-icon"></i>
                  <select class="user__form-input  user__form-input--select <?=($this->getValue($field, 'required', false, true))?'f_required':''?>" data-id="<?=$this->getId($field)?>" name="field[<?=$this->getId($field)?>]" >
                    <option value=""> </option>
                  </select>
              </div>
      <?  
          break;
          default:?>
              <label class="user__form-label" for=""><?=$this->getValue($field, 'name', false, true)?> <?=($this->getValue($field, 'required', false, true))?'<span style="color: red">*</span>':''?></label>
              <div class="user__form-select">
                  <i class="fas fa-angle-down user__fas-icon"></i>
                  <select class="user__form-input user__form-input--select" name="">
                      <option value="Услуга 1">Услуга 1</option>
                      <option value="Услуга 2">Услуга 2</option>
                      <option value="Услуга 3">Услуга 4</option>
                  </select>
              </div>
     
      <? }?>
        </div>
  
  
  
  
      <? if ($row_size<=0){
          echo '</div>';
          $items_in_row=0;
          $row_size=6;
         }
      ?>
      
      
      <?php endforeach;?>
        <? //TODO передалать последний ша 
      if ($groups_count==1){?>
      <div class="user__bottom-btn">
        <button class="user__inner-btn user__inner-btn--form user__inner-btn--bottom end_user_button"><?=$this->getValue($_RESPONSE['form'], 'end_button', false);?></button>
      </div>
      <?}?>
  
      <? if ($groups_count>1){?>
        <div class="user__bottom-btn user__bottom-btn--master">
           <? if ($this->getId($_RESPONSE['form'])==7 && $level==3){?>
            <span data-level="1" class="user__inner-btn user__inner-btn--form user__inner-btn--bottom p-lg" onclick="getCalendarModule();">Далее</span>
           <?}else{?>
            <span data-level="1" class="user__inner-btn user__inner-btn--form user__inner-btn--form_next user__inner-btn--bottom p-lg">Далее</span>
          <?}?>
        </div>
      <?}?>
    </div>
<? $level++; ?>
<?php endforeach;?>

<? if ($this->getId($_RESPONSE['form'])==7){
  ?>
<div class="user__form-level">
                                                <div class="user__form-result">
                                                    <ul class="user__form-result-list">
                                                        <li class="user__form-result-item">
                                                            <p class="user__form-result-inner">Фамилия</p>
                                                            <p class="user__form-result-inner" id="res_72">Иванов</p>
                                                        </li>
                                                        <li class="user__form-result-item">
                                                            <p class="user__form-result-inner">Имя</p>
                                                            <p class="user__form-result-inner" id="res_73">Иван</p>
                                                        </li>
                                                        <li class="user__form-result-item">
                                                            <p class="user__form-result-inner">Отчество</p>
                                                            <p class="user__form-result-inner" id="res_74"> Иванович</p>
                                                        </li>
                                                        <li class="user__form-result-item">
                                                            <p class="user__form-result-inner">Дата Рождения</p>
                                                            <p class="user__form-result-inner" id="res_75"> 01.01.2000</p>
                                                        </li>
                                                        <li class="user__form-result-item">
                                                            <p class="user__form-result-inner">Паспорт</p>
                                                            <p class="user__form-result-inner" id="res_76">1234 567891</p>
                                                        </li>
                                                        <li class="user__form-result-item">
                                                            <p class="user__form-result-inner">СНИЛС</p>
                                                            <p class="user__form-result-inner" id="res_77">123456789</p>
                                                        </li>

                                                        <li class="user__form-result-item">
                                                            <p class="user__form-result-inner">Адрес электронной почты</p>
                                                            <p class="user__form-result-inner" id="res_78">ivan@ivanov.ru</p>
                                                        </li>
                                                        <li class="user__form-result-item">
                                                            <p class="user__form-result-inner">Номер телефона</p>
                                                            <p class="user__form-result-inner" style="font-weight: 700; color: #2C2A29;" id="res_79">8 800 555 3535</p>
                                                        </li>

                                                        <li class="user__form-result-item">
                                                            <p class="user__form-result-inner">Тип заявителя</p>
                                                            <p class="user__form-result-inner" id="res_80">Физическое лицо</p>
                                                        </li>
                                                        <li class="user__form-result-item">
                                                            <p class="user__form-result-inner">Услуга</p>
                                                            <p class="user__form-result-inner" id="res_54">Получение результата услуги</p>
                                                        </li>
                                                        <li class="user__form-result-item">
                                                            <p class="user__form-result-inner">Офис МФЦ </p>
                                                            <p class="user__form-result-inner" id="res_56">Свердловская область, г. Екатеринбург</p>
                                                        </li>
                                                        <li class="user__form-result-item">
                                                            <p class="user__form-result-inner" style="font-weight: 700; color: #58595B;">Дата предварительной записи</p>
                                                            <p class="user__form-result-inner" style="color: #E04E39;" id="res_date">01.01.2000</p>
                                                        </li>
                                                        <li class="user__form-result-item">
                                                            <p class="user__form-result-inner" style="font-weight: 700; color: #58595B;">Время предварительной записи</p>
                                                            <p class="user__form-result-inner" style="color: #E04E39;" id="res_time">12:00</p>
                                                        </li>
                                                       
                                                    </ul>
                                                    <p class="user__form-result-description">Заявленное количество обращений<br> по услуге на подачу документов или получение результата — <span id="res_docs_count">1</span></p>
                                                    <div class="user__form-item">
                                                        <label class="user__inner-text user__inner-text--input" for="level"><input id="level" class="f_required" type="checkbox">&nbsp; Подтверждаю, что данные внесены верно<span style="color: red">*</span></label>
                                                    </div>
                                                    <div class="user__bottom-btn user__bottom-btn--master">
                                                        <a class="user__inner-btn user__inner-btn--form user__inner-btn--bottom p-lg" onclick="submit_reservation();">Зарегистрировать запись</a>
                                                    </div>
                                                </div>
                                            </div>
<?
}
?>


<input type="hidden" name="form" value="<?=$this->getId($_RESPONSE['form'])?>">
  
</form>


<script src="/js/webcam.min.js"></script>
<link rel="stylesheet" href="/css/calendar.css">
