<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>
<!doctype html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Админка</title>
    <!-- <script src="https://cdn.tiny.cloud/1/7spoku6e9mzn116oxd88y03rtzvaa57t8p0sr6b8ci0ge3kz/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script> -->
    <link rel="stylesheet" href="/admin_tpls/assets/libs/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/admin_tpls/assets/libs/bootstrap-multiselect/css/bootstrap-multiselect.css">
    <link rel="stylesheet" href="/admin_tpls/assets/css/styles.css">

    <style>
        @import url('/fonts/circe.fonts.css'); @import url('/fonts/ptsans.fonts.css')
    </style>
</head>
<body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="/"><?=$this->getSetting('site_name')?></a>
        <?php
            if($this->module == 'guides' and $this->method == 'list_items'){ $searchAction = '/admin/guides/list_items/'.$this->params[0].'/';}
            else{$searchAction = '/admin/'.$this->module.'/lists/';}
        ?>
        <form action="<?=$searchAction?>" method="GET" style="width: 500px">
            <input class="" name="search" type="text" placeholder="Поиск по элементам текущего модуля" style="width: 400px"><button style="display: inline-block">OK</button>
        </form>

        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                <a class="nav-link" href="/users/logout">Выйти</a>
            </li>
        </ul>
    </nav>
    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <div class="sidebar-sticky">
                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Объекты и данные</span>
                    </h6>
                    <?php $guidesInMenu = $this->macros('guides','lists',array(false,true));?>
                    <ul class="nav flex-column">
                        <?php if(isset($guidesInMenu['data'])):?>
                            <?php foreach($guidesInMenu['data'] as $guideInMenu):?>
                                <?php
                                if($guideInMenu->getValue('is_module')){
                                    if($this->macros('permissions', 'checkPermission', [$guideInMenu->getName(), 'lists', router::$currentUser->getValue('type')])){
                                        $guideHref = '/admin/'.$guideInMenu->getName().'/lists';
                                    }
                                    else{ continue;}
                                }
                                else{ $guideHref = '/admin/guides/list_items/'.$guideInMenu->getId();}
                                ?>
                                <li class="nav-item">
                                    <a href="<?=$guideHref?>" class="nav-link">
                                        <?php if($iconClass = $guideInMenu->getValue('icon_class')):?>
                                            <span data-feather="<?=$iconClass?>"></span>
                                        <?php endif;?>
                                        <?=$guideInMenu->getValue('descr')?>
                                    </a>
                                </li>
                            <?php endforeach;?>
                        <?php endif;?>
                    </ul>

                    <?php if($this->macros('permissions', 'checkPermission', ['guides', 'lists', router::$currentUser->getValue('type')])):?>
                        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                            <span>Справочники</span>
                            <a class="d-flex align-items-center text-muted" href="/admin/guides/add" aria-label="Добавить справочник" title="Добавить справочник">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
                            </a>
                        </h6>
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a class="nav-link" href="/admin/guides/lists">
                                    <span data-feather="list"></span> Просмотр справочников
                                </a>
                            </li>
                        </ul>
                    <?php endif;?>

                    <?php if(router::$currentUser->isAdmin()):?>
                        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                            <span>Прочее</span>
                        </h6>
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a class="nav-link" href="/admin/pages/list_fields">
                                    <span data-feather="list"></span> Дополнительные поля для страниц
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/admin/permissions/lists">
                                    <span data-feather="list"></span> Разрешения
                                </a>
                            </li>
                            <!--<li class="nav-item">
                                <a class="nav-link" href="/admin/cacher/control">
                                    <span data-feather="list"></span> Кэширование запросов
                                </a>
                            </li>-->
                        </ul>
                    <?php endif;?>
                </div>
            </nav>
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                <?php if(isset($_GET['success'])):?>
                    <div class="alert alert-success" role="alert">
                        <?php if($_GET['success'] > 0):?>
                            Данные сохранены успешно!
                        <?php else:?>
                            Нет изменений
                        <?php endif;?>
                    </div>
                <?php endif;?>
                <?php if(isset($_GET['err'])):?>
                    <div class="alert alert-danger" role="alert">
                        Произошла ошибка.
                    </div>
                <?php endif;?>
                <?php $this->getTemplate($this->module,$this->method,$_RESPONSE)?>
            </main>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script>
        window.jQuery || document.write('<script src="/docs/4.4/assets/js/vendor/jquery.slim.min.js"><\/script>')
    </script>
    <script src="/admin_tpls/assets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/admin_tpls/assets/libs/Sortable.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.24.1/feather.min.js"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script> -->
    <!-- <script src="/js/libs.min.js"></script> -->
    <!-- <script src="/js/action.js"></script> -->

    <script>
        var site = {
            module: '<?=$this->module?>',
            method: '<?=$this->method?>',
            <?php if(router::$currentUser):?>
                user: {
                    type: '<?=router::$currentUser->getValue('type')?>',
                    id: <?=router::$currentUser->getId()?>
                },
            <?php endif;?>

            <?php if(isset($_RESPONSE['guide'])):?>
                guideId: <?=$_RESPONSE['guide']->getId()?>,
            <?php endif;?>

            <?php if(isset($_RESPONSE['edit'])):?>
                editId: <?=$_RESPONSE['edit']->getId()?>
            <?php endif;?>
        }
    </script>
    <script src="/admin_tpls/assets/libs/tinymce/js/tinymce/tinymce.min.js"></script>
    <script src="/admin_tpls/assets/libs/bootstrap-multiselect/js/bootstrap-multiselect.js"></script>
    <script src="/admin_tpls/assets/js/script.js"></script>
    <script src="/admin_tpls/assets/js/dashboard.js"></script>
    <?php if(file_exists(SITE_ROOT.'/admin_tpls/assets/js/'.$this->module .'.js')):?>
        <script src="/admin_tpls/assets/js/<?= $this->module ?>.js?v=<?=time()?>"></script>
    <?php endif;?>

    <script>feather.replace();</script>
</body>
</html>