<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>

<div class="main_content_container">
    <h1>Новая настройка</h1>
    <form action="/admin/settings/add/" method="POST" id="form" enctype="multipart/form-data">
        <div class="form-group row">
            <label for="input_name" class="col-sm-4 col-xl-3 col-form-label">Системное название</label>
            <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                <input required="" class="form-control" type="text" name="name" value="" id="input_name">
            </div>
        </div>

        <div class="form-group row">
            <label for="input_name" class="col-sm-4 col-xl-3 col-form-label">Описание</label>
            <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                <input type="text" class="form-control" name="descr" id="input_descr" value="">
            </div>
        </div>

        <div class="form-group row">
            <label for="input_name" class="col-sm-4 col-xl-3 col-form-label">Тип</label>
            <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                <select name="type">
                    <option value="string">Строка</option>
                    <option value="boolean">Галочка</option>
                </select>
            </div>
        </div>

        <div class="form_buttons">
            <div class="row">
                <div class="col-6">
                    <button class="btn btn-success">Сохранить</button>
                </div>
            </div>
        </div>
    </form>
</div>