<? /** @var templater $this */ ?><? /** @var array $_RESPONSE */ ?>
<form action="/webforms/send/<?=$_RESPONSE['form_id']?>"  method="POST" class="contacts__form" enctype="multipart/form-data">
    <?php foreach($_RESPONSE['fields'] as $input):?>
        <?php switch($input['type']){
            case 'varchar': ?>
                <input type="text" name="<?=$input['name']?>" class="contacts__input" placeholder="<?=$input['descr']?>">
            <?php break;

            case 'text': ?>
                <textarea name="<?=$input['name']?>" class="contacts__input" placeholder="<?=$input['descr']?>"></textarea>
            <?php break;

            case 'date': ?>
                <input type="date" name="<?=$input['name']?>" class="contacts__input" placeholder="<?=$input['descr']?>">
            <?php break;

            case 'datetime': ?>
                <input type="datetime-local" name="<?=$input['name']?>" class="contacts__input" placeholder="<?=$input['descr']?>">
            <?php break;

            case 'int': ?>
                <input type="number" step="1" name="<?=$input['name']?>" class="contacts__input" placeholder="<?=$input['descr']?>">
            <?php break;

            case 'float': ?>
                <input type="number" name="<?=$input['name']?>" class="contacts__input" placeholder="<?=$input['descr']?>">
            <?php break;

            case 'boolean': ?>
                <?=$input['descr']?>:
                <input type="checkbox" name="<?=$input['name']?>" class="contacts__input" value="1">
            <?php break;

            case 'file': ?>
                <div class="contacts__form-wrapper">
                    <input type="file" name="<?=$input['name']?>" id="upload_<?=$input['name']?>" class="contacts__upload">
                    <label for="upload_<?=$input['name']?>" class="contacts__label"><?=$input['descr']?></label>
                </div>
            <?php break;

            case 'list': ?>
                <?=$input['descr']?>:
                <select name="<?=$input['name']?>">
                    <?php foreach($input['list'] as $item):?>
                        <option><?=$item?></option>
                    <?php endforeach;?>
                </select>
            <?php break;
        }
        ?>
    <?php endforeach;?>

    <?php if(isset($_RESPONSE['pageId'])):?>
        <input type="hidden" name="from_page" value="<?=$_RESPONSE['pageId']?>">
    <?php endif;?>

    <div class="contacts__form-wrapper">
        <button type="submit" class="btn btn--arrow contacts__btn">отправить</button>
    </div>
</form>