<div class="modal" id="modal-send-js" style="display: none;">
    <div class="modal__card-inner">
        <div class="modal__card modal__card--leave">
            <h5 class="modal__card-title modal__card-title--leave"><?=$_RESPONSE['title']?></h5>
            <form action="/webforms/send/<?=$_RESPONSE['form']['form_id']?>" method="POST" enctype="multipart/form-data">
                <div class="user__form-item">
                    <label class="user__form-label" for="">ФИО</label>
                    <div><input class="user__form-input" name="fio" type="text" placeholder=""></div>
                </div>
                <div class="user__wrap-form-item user__wrap-form-item--leave">
                    <div class="user__form-item user__form-item--wrap user__form-item--fluid">
                        <label class="user__form-label" for="">Номер телефона<span style="color: red">*</span></label>
                        <div><input required="" class="user__form-input" name="phone" type="text" placeholder=""></div>
                    </div>
                    <div class="user__form-item user__form-item--wrap user__form-item--fluid">
                        <label class="user__form-label" for="">Электронная почта (при наличии)</label>
                        <div><input class="user__form-input" name="email" type="text" placeholder=""></div>
                    </div>
                </div>
                <div class="user__form-item">
                    <label class="user__form-label" for="">Предпочтительное время для связи</label>
                    <div><input class="user__form-input" name="time" type="text" placeholder=""></div>
                </div>

                <input type="hidden" name="from_page" value="<?=$_SERVER['REQUEST_URI']?>">

                <div class="user__bottom-btn">
                    <button class="user__inner-btn user__inner-btn--form user__inner-btn--bottom"><?=$_RESPONSE['btn_name']?></button>
                </div>
            </form>
            <span class="modal__card-close" id="modal-close-js"><i class="fas fa-times"></i></span>
        </div>
    </div>
</div>