<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
	<h1 class="h2">Список файлов</h1>
</div>
<table class="table table-striped table-sm numered">
	<thead>
		<tr>
			<th>#</th>
			<th>Название</th>
		</tr>
	</thead>
	<tbody>
        <?php if($_RESPONSE['data']):?>
            <?php foreach($_RESPONSE['data'] as $k=>$file):?>
            <tr>
                <td><?=$k+1?></td>
                <td><a href="/files/download/<?=$file->getId()?>"><?=$file->getName()?></a></td>
            </tr>
            <?php endforeach;?>
        <?php else:?>
            <tr>
                <td></td><td>Нет данных для отображения</td>
            </tr>
        <?php endif;?>
	</tbody>
</table>