<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>

<div class="main_content_container">
    <h1>Редактировать <span id="itemName">«<?=$_RESPONSE['edit']->getName()?>»</span></h1>

    <?php if($_RESPONSE['guide']->getValue('is_module')){ $form_action = '/admin/'.$_RESPONSE['guide']->getName().'/edit/'.$_RESPONSE['edit']->getId();}
    else { $form_action = "/admin/guides/edit_item/".$_RESPONSE['guide']->getId()."/".$_RESPONSE['edit']->getId();}

    ?>
    <ul class="nav nav-tabs" id="guideTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="main-tab" data-toggle="tab" href="#mainInfo" role="tab" aria-controls="main" aria-selected="true">Основные данные</a>
        </li>
        <li class="nav-item pageTab" <?=(!$_RESPONSE['appendedPage']) ? 'style="display:none"':''?>>
            <a class="nav-link" id="page-tab" data-toggle="tab" href="#pageInfo" role="tab" aria-controls="page" aria-selected="false">Страница</a>
        </li>
    </ul>
    <form action="<?=$form_action?>" method="POST" id="form" enctype="multipart/form-data">

        <?php $fields = $_RESPONSE['edit']->getValue('_guideFields');?>

        <div class="tab-content" id="guideTabContent">
            <div class="tab-pane fade show active" id="mainInfo" role="tabpanel" aria-labelledby="main-tab">
                <table>
                    <tr>
                        <td width="30%">
                            Данные с API

                            <pre style="    max-height: 600px; max-width: 500px; overflow: scroll; position: relative;">
                                <?php print_r($_RESPONSE['api']);?>
                            </pre>
                        </td>

                        <td width="70%">

                            <div class="form-group row">
                                <label for="input_name" class="col-sm-4 col-xl-3 col-form-label">Название</label>
                                <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                                    <input required class="form-control" type="text" name="name" value="<?=$_RESPONSE['edit']->getName()?>" id="input_name">
                                </div>
                            </div>

                            <?php $objData = array('guide'=>$_RESPONSE['guide']->getId(), 'item'=>$_RESPONSE['edit']->getId())?>
                            <?php foreach($fields as $field):?>
                                <?php if($field['name'] == 'category'):?>
                                    <div class="form-group row">
                                        <label for="input_create_page" class="col-sm-4 col-xl-3 col-form-label"><?=$field['descr']?></label>
                                        <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                                            <?php
                                            $globalCategories = $this->macros('guides','list_items', ['service_categories_groups', false, false, 'ASC', 'name', true]);
                                            if($category = $this->macros('guides', 'get_item', [19, $this->getValue($_RESPONSE['edit'], 'category')])){
                                                $groupId = $this->getValue($category, 'group');
                                                $otherCategoriesInGroup = $this->macros('services','loadCategories', [$groupId]);
                                            }
                                            else{ $groupId = 0;}
                                            ?>

                                            <select id="group">
                                                <option value="0">Не выбрано</option>
                                                <?php foreach($globalCategories['data'] as $group):?>
                                                    <option <?=$this->optSel($groupId, $this->getId($group))?> value="<?=$this->getId($group)?>"><?=$this->getName($group)?></option>
                                                <?php endforeach;?>
                                            </select>

                                            <select name="category">
                                                <?php if($category):?>
                                                    <?php foreach($otherCategoriesInGroup['data'] as $otherCat):?>
                                                        <option <?=$this->optSel($otherCat->getId(), $category->getId())?> value="<?=$this->getId($otherCat)?>" selected><?=$this->getName($otherCat)?></option>
                                                    <?php endforeach;?>
                                                <?php else:?>
                                                    <option value="0">Сначала выберите группу категорий</option>
                                                <?php endif;?>
                                            </select>
                                        </div>
                                    </div>
                                <?php else:?>
                                    <?php $this->getTemplate('guides','format_fields', array('field'=>$field, 'value'=>$_RESPONSE['edit']->getValue($field['name']), 'object'=>$objData))?>
                                <?php endif;?>
                            <?php endforeach;?>
                        </td>
                    </tr>



            </div>

        </div>
        <div class="form_buttons">
            <div class="row">
                <?php if($_RESPONSE['appendedPage']):?>
                    <div class="col-auto">
                        <a id="watchOnSite" class="btn btn-outline-dark" target="_blank" href="/<?=$_RESPONSE['appendedPage']->getValue('lang')?>/<?=$_RESPONSE['appendedPage']->getValue('url')?>" title="Посмотреть страницу на сайте"><span data-feather="eye"></span></a>
                    </div>
                <?php endif;?>

                <?php
                if($_RESPONSE['appendedPage']){
                    $this->getTemplate('pages','langSwitcher',array('pageId'=>$_RESPONSE['appendedPage']->getId(),'lang'=>$_RESPONSE['appendedPage']->getValue('lang'),'fromModule'=>$_RESPONSE['edit']->getObjectClassName()));
                }
                else{
                    $this->getTemplate('pages','langSwitcher',array('lang'=>$_RESPONSE['edit']->getValue('lang'),'fromModule'=>$_RESPONSE['edit']->getObjectClassName()));
                }
                ?>

                <div class="col-auto">
                    <button class="btn btn-success saveOutpost">Сохранить</button>
                </div>
                <div class="col-auto">
                    <a class="btn btn-danger" href="/admin/guides/del_item/<?=$_RESPONSE['guide']->getId()?>/<?=$_RESPONSE['edit']->getId()?>">Удалить</a>
                </div>
            </div>
        </div>
    </form>
</div>