<section class="main-content">
    <div class="container">
        <div class="main-content__inner">
            <?php $this->getTemplateByFile('./templates/pages/parts/aside.phtml',[])?>
            <main class="main main-content__main">
                <div class="showcase">
                    <div class="showcase__content">
                        <div>
                            <h1 class="showcase__title showcase__title--services">Объявления</h1>
                        </div>
                        <div class="showcase__number showcase__number--announce">
                            <?php $this->getTemplateByFile('./templates/pages/parts/svgs.phtml', ['what'=>'notices'])?>
                        </div>
                    </div>
                </div>
                <?php $notices = $this->macros('guides', 'list_items', ['notices', false, true]);?>
                <div class="">
                    <div class="announce">
                        <ul class="breadcrumbs offers__breadcrumbs">
                            <li class="breadcrumbs__item">Главная  </li>
                            <li class="breadcrumbs__item"> Объявления</li>
                        </ul>
                        <div class="announce__inner">
                            <?php foreach($notices['data'] as $notice):?>
                                <a href="#" class="announce__item send-code" data-id="<?=$this->getId($notice)?>">
                                    <p class="announce__text">
                                        <?=$this->getName($notice)?>
                                    </p>
                                    <span class="announce__date"><?=$this->formatDate($this->getValue($notice, 'create_time'))?></span>
                                </a>
                            <?php endforeach;?>
                        </div>
                        <?php $this->getTemplateByFile('./templates/pages/parts/numpages.phtml', ['total'=>$notices['total']])?>

                    </div>
                </div>
            </main>
        </div>
    </div>
</section>

<div class="modal" id="modal-send-js">
    <div class="modal__card-inner">
        <div class="modal__card">
            <h5 class="modal__card-title modal__card-title--announce">title</h5>
            <p class="modal__card-text">text</p>
            <span class="modal__card-date">date</span>
            <span class="modal__card-close" id="modal-close-js"><i class="fas fa-times"></i></span>
        </div>
    </div>
</div>