<?php if(isset($_RESPONSE['page'])){ $checkStatus = $this->macros('services','check_status',[]);}
else{ $checkStatus = $_RESPONSE;}
?>

<section class="main-content">
    <div class="container">
        <div class="main-content__inner">
            <?php $this->getTemplateByFile('./templates/pages/parts/aside.phtml',[])?>
            <main class="main main-content__main">
                <div class="showcase">
                    <div class="showcase__content">
                        <div>
                            <h1 class="showcase__title showcase__title--directories">Проверка статуса услуги</h1>
                        </div>
                        <div class="showcase__number showcase__number--jobs">
                            <?php $this->getTemplateByFile('./templates/pages/parts/svgs.phtml', ['what'=>'check_status'])?>
                        </div>
                    </div>
                </div>
                <div class="">
                    <div class="offers  offers--new">
                        <ul class="breadcrumbs offers__breadcrumbs offers__breadcrumbs--jobs">
                            <li class="breadcrumbs__item">Главная  </li>
                            <li class="breadcrumbs__item">Проверка статуса услуги</li>
                        </ul>
                    </div>
                    <div class="search">
                        <h4 class="search__title">Введите номер заявки, чтобы узнать статус обращения</h4>
                        <form action="/services/check_status" method="GET" class="search__form">
                            <div class="search_row-item">
                                <label class="search__form-label" for="number">Номер заявки</label>
                                <div>
                                    <input class="search__form-input" type="text" id="number" name="number" value="<?=(isset($_GET['number'])) ? htmlspecialchars($_GET['number']) : '' ?>">
                                </div>
                            </div>
                            <button class="search__form-btn send-code" >Отправить</button>
                        </form>

                        <div class="applyResult">
                        <?php if($checkStatus):?>
                            Статус вашей заявки: <?=$checkStatus['status']?>
                        <?php else:?>
                            <?php if(isset($_GET['number'])):?>
                                <div class="applyResult">Заявка не найдена</div>
                            <?php endif;?>
                        <?php endif;?>
                    </div>
                </div>
            </main>
        </div>
    </div>
</section>

<div class="modal applyInfoModal" id="modal-send-js">
    <div class="modal__card-inner">
        <div class="modal__card">
            <h5 class="modal__card-title">Заявка № <span id="applyNumber"></span></h5>
            <p class="modal__card-text">Статус заявки: <strong style="font-weight: bold;" id="applyStatus">На рассмотрении</strong></p>
            <p class="modal__card-text">Ожидаемая дата выдачи: <span style="font-weight: bold;" id="applyEndDate"></span></strong></p>
            <span class="modal__card-date" id="applyStartDate"></span>
            <span class="modal__card-close" id="modal-close-js"><i class="fas fa-times"></i></span>
        </div>
    </div>
</div>