<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>
<style>
    .offers__list{ border: none;}

    .offers__list-item {
        border: 2px solid #C39367;
        margin-bottom: 20px;
    }
</style>
<section class="main-content">
    <div class="container">
        <div class="main-content__inner">
            <?php $this->getTemplateByFile('./templates/pages/parts/aside.phtml',[])?>
            <main class="main main-content__main">
                <div class="showcase">
                    <div class="showcase__content">
                        <div>
                            <h1 class="showcase__title showcase__title--services">Услуги</h1>
                        </div>
                        <div class="showcase__number showcase__number--services">
                            <?php $this->getTemplateByFile('./templates/pages/parts/svgs.phtml', ['what'=>'services'])?>
                        </div>
                    </div>
                </div>
                <div class="">
                    <div class="offers">
                        <ul class="breadcrumbs offers__breadcrumbs">
                            <li class="breadcrumbs__item">Главная  </li>
                            <li class="breadcrumbs__item">Услуги</li>
                            <li class="breadcrumbs__item"><?=$this->getName($_RESPONSE['source'])?></li>
                        </ul>
                        <h2 class="offers__title"><?=$this->getName($_RESPONSE['source'])?></h2>
                        <ul class="box-service offres__nav-box">
                            <?php if($gosuslugi_link = $this->getValue($_RESPONSE, 'gosuslugi_link')):?>
                                <li class="box-service__item box-service__item--off">
                                    <div class="box-service__type">
                                        <h4 class="box-service__name">Портал Госуслуг</h4>
                                        <svg class="box-service__icon box-service__icon--1"><use xlink:href="/sprite.svg#of1"></use></svg>
                                    </div>
                                    <a href="<?=$gosuslugi_link?>" class="box-service__btn">Подать в электронной форме</a>
                                </li>
                            <?php endif;?>

                            <?php if($mfc_link = $this->getValue($_RESPONSE, 'mfc_link')):?>
                                <li class="box-service__item">
                                    <div class="box-service__type">
                                        <h4 class="box-service__name">В отделении МФЦ</h4>
                                        <svg class="box-service__icon box-service__icon--2"><use xlink:href="/sprite.svg#of2"></use></svg>
                                    </div>
                                    <a href="<?=$mfc_link?>" class="box-service__btn">Записаться на приём</a>
                                </li>
                            <?php endif;?>

                            <?php if($ministry_link = $this->getValue($_RESPONSE, 'ministry_link')):?>
                                <li class="box-service__item">
                                    <div class="box-service__type">
                                        <h4 class="box-service__name">В органе (организации)</h4>
                                        <svg class="box-service__icon box-service__icon--3"><use xlink:href="/sprite.svg#of3"></use></svg>
                                    </div>
                                    <a href="<?=$ministry_link?>" class="box-service__btn">Получить информацию</a>
                                </li>
                            <?php endif;?>
                        </ul>

                        <?php if($subservices = $this->getValue($_RESPONSE['source'], 'subservices')):?>
                            <div class="offers__bar">Выберите услугу:</div>
                            <ul class="offers__list">
                                <?php
                                // системное название поля => [русское название поля, отобразить как список, отобразить кнопку]
                                $infoFields = [
                                    'descr'=> ['Краткое описание', 0, 0],
                                    'for'=> ['Кому предоставляется услуга', 1, 0],
                                    'docs'=> ['Необходимые документы', 1, 0],
                                    'for_presenter'=> ['Для представителей', 0, 0],
                                    'time'=> ['Срок предоставления', 0, 0],
                                    'price'=> ['Стоимость услуги и порядок оказания', 0, 1],
                                    'result'=> ['Результат оказания услуги', 1, 0],
                                    'ministry'=> ['Орган, предоставляющий услугу',0,0]
                                ];?>
                                <?php foreach($subservices as $subService):?>
                                    <li class="offers__list-item">
                                        <div class="offers__list-title offers-title-js"><span><?=$this->getName($subService)?></span> <span class="offers__wrap-icon"><i class="fas fa-plus offers__plus-icon"></i><i class="fas fa-minus offers__minus-icon"></i></span></div>
                                        <div class="offers__sublist">
                                            <ul>
                                                <?php foreach($infoFields as $fieldName=>$fieldProps):?>
                                                    <?php if($fieldValue = $this->getValue($subService, $fieldName)):?>
                                                        <li class="offers__sublist-item">
                                                            <h5 class="offers__sublist-title"><?=$fieldProps[0]?>:</h5>
                                                            <?php if($fieldProps[1] == 0):?>
                                                                <p class="offers__sublist-description"><?=$fieldValue?></p>
                                                            <?php else:?>
                                                                <?php $bylines = explode("\r\n", $fieldValue);?>
                                                                <?php foreach($bylines as $line):?>
                                                                    <p class="offers__sublist-text"><?=$line?></p>
                                                                <?php endforeach;?>
                                                            <?php endif;?>
                                                            <?php if($fieldProps[2] == 1):?>
                                                                <button class="offers__sublist-btn">Оплатить</button>
                                                            <?php endif;?>
                                                        </li>
                                                    <?php endif;?>
                                                <?php endforeach;?>
                                            </ul>

                                            <ul class="box-service offres__nav-box">
                                                <?php if($gosuslugi_link = $this->getValue($subService, 'gosuslugi_link')):?>
                                                    <li class="box-service__item">
                                                        <div class="box-service__type">
                                                            <h4 class="box-service__name">Портал Госуслуг</h4>
                                                            <svg class="box-service__icon box-service__icon--1"><use xlink:href="/sprite.svg#of1"></use></svg>
                                                        </div>
                                                        <a href="<?=$gosuslugi_link?>" class="box-service__btn">Подать в электронной форме</a>
                                                    </li>
                                                <?php endif;?>

                                                <?php if($mfc_link = $this->getValue($subService, 'mfc_link')):?>
                                                    <li class="box-service__item">
                                                        <div class="box-service__type">
                                                            <h4 class="box-service__name">В отделении МФЦ</h4>
                                                            <svg class="box-service__icon box-service__icon--2"><use xlink:href="/sprite.svg#of2"></use></svg>
                                                        </div>
                                                        <a href="<?=$mfc_link?>" class="box-service__btn">Записаться на приём</a>
                                                    </li>
                                                <?php endif;?>

                                                <?php if($ministry_link = $this->getValue($subService, 'ministry_link')):?>
                                                    <li class="box-service__item">
                                                        <div class="box-service__type">
                                                            <h4 class="box-service__name">В органе (организации)</h4>
                                                            <svg class="box-service__icon box-service__icon--3"><use xlink:href="/sprite.svg#of3"></use></svg>
                                                        </div>
                                                        <a href="<?=$ministry_link?>" class="box-service__btn">Получить информацию</a>
                                                    </li>
                                                <?php endif;?>
                                            </ul>
                                        </div>
                                    </li>
                                <?php endforeach;?>
                            </ul>
                        <?php endif;?>
                    </div>
                </div>
            </main>
        </div>
    </div>
</section>