<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>

<style>
  .btn-group, .btn-group-vertical{display:block!important}
  .card-body .row:not(:first-child){border-top: 1px solid #aaa;padding-top: 13px;}
  .multiselect-container.dropdown-menu.show {height: auto!important;max-height: 350px;
</style>
<script>
document.addEventListener('DOMContentLoaded', function(){
  
  if ($("#sections").find('.ex_section').length==0){
    $("#sections").append($(".ex_section").html());
    $('#sections').find("input[name='fields[name][]']").attr('name', 'new_fields[name][]');
    $('#sections').find("input[name='fields[required][]']").attr('name', 'new_fields[required][]');
    $('#sections').find("select[name='fields[type][]']").attr('name', 'new_fields[type][]');
    $('#sections').find("select[name='fields[width][]']").attr('name', 'new_fields[width][]');
    $('#sections').find("input[name='fields[section][]']").attr('name', 'new_fields[section][]');
  }
  count_section();
  $("#sections").find("select").addClass('form-control');

  $('.add_section_row').click(function(){
      //$(".ex_section").find('.del_section').show();
      $("#sections").append('<div class="ex_section new_section">'+$(".ex_section").html()+'</div>');
      count_section();
      $("#sections").find("select").addClass('form-control');
      set_new_fields('.new_section');
    });
  
  
  

  
  $("#form").submit(function(evt) {
    //handleChecbox
    $('input:checkbox').each(function(){
      if ($(this).is(':checked')){
        $(this).val(1);
      }else{
        $(this).val(0);
      }
    });
    $('.form_row input:checkbox').prop('checked', true);
    //evt.preventDefault();
});

// standard on load code goes here with $ prefix
// note: the $ is setup inside the anonymous function of the ready command
});
  
  function extra_field_select(that){
    $(that).parents('.form_row').find('.extra_field').val($(that).val());
  }
  
  function typeselect(that){

    if (($(that).val()=='guide') || ($(that).val()=='guide_ajax') || ($(that).val()=='guide_ajax_empty')){
      console.log($(that).val());
      $(that).parents('.form-group').find('.extra_field_select').show();
    }else{
      $(that).parents('.form-group').find('.extra_field_select').hide();
    }
    $('select.form-control').multiselect();
  }
  
  function set_new_fields(el){
    $(el).find("input[name='fields[name][]']").attr('name', 'new_fields[name][]');
    $(el).find("input[name='fields[required][]']").attr('name', 'new_fields[required][]');
    $(el).find("select[name='fields[type][]']").attr('name', 'new_fields[type][]');
    $(el).find("select[name='fields[width][]']").attr('name', 'new_fields[width][]');
    $(el).find("input[name='fields[section][]']").attr('name', 'new_fields[section][]');
  }
  
   function add_field_row(that){
      card_body= $(that).parents('.card').find('.card-body');
      card_body.append('<div class="row row_line appended">'+$(".ex_section").find('.form_row').html()+'</div>');
     set_new_fields('.appended');
     
      card_body.find("select").addClass('form-control');
     count_section();
      //card_body.("select").multiselect("refresh");
    // $('select[name="field_type"]').multiselect("refresh");
    };
  
  function count_section(){
    section_counter = 1;
    $("#sections .card").each(function() {
      $( this ).find('.card-title').html('Шаг '+section_counter);
       $( this ).find('.row_section').val(section_counter);
      section_counter++;
    });
  }
  
  function del_section_row(that){
      if (confirm("Вы подтверждаете удаление?")) {
        $(that).parents('.card').remove();
        count_section();
      }
    };
  
  function del_field_row(that,id=0){
      if (confirm("Вы подтверждаете удаление?")) {
        if (id>0){
          $('#div_del').append('<input type="hidden" name="form_row_delete[]" value="'+id+'">');
        }     

        console.log($(that).parents('.card-body').find('.form_row').length);
        if ($(that).parents('.card-body').find('.form_row').length==1){
          $(that).parents('.ex_section').remove();
        }else{
          $(that).parent().parent().remove();
        }
        count_section();
      }
    } 

</script>

<?php $editMode = isset($_RESPONSE['edit']);

$this->getTemplate('formgenerator', 'section', []);?>

<!--Код из guides -> add_item -->
<div class="main_content_container">
 <? if ($editMode) { ?>
    <h1>Редактировать <span id="itemName">«<?=$_RESPONSE['edit']->getName()?>»</span></h1>
 <? }else{ ?>
    <h1>Добавление <span id="itemName"></span></h1>
 <? } ?>
  
    <?php if($_RESPONSE['guide']->getValue('is_module')){ 
              if ($editMode){
                $form_action = '/admin/'.$_RESPONSE['guide']->getName().'/edit/'.$_RESPONSE['edit']->getId();
              }else{
                $form_action = '/admin/'.$_RESPONSE['guide']->getName().'/add/';}  
              }
          else { 
              $form_action = "/admin/guides/add_item/".$_RESPONSE['guide']->getId();
          }
    ?>
    <ul class="nav nav-tabs" id="guideTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="main-tab" data-toggle="tab" href="#mainInfo" role="tab" aria-controls="main" aria-selected="true">Основные данные</a>
        </li>
    </ul>
    <form action="<?=$form_action?>" method="POST" id="form" enctype="multipart/form-data">
        <?php $fields = ($editMode) ? $_RESPONSE['edit']->_guideFields : $_RESPONSE['fields'];?>

        <div class="tab-content" id="guideTabContent">
            <div class="tab-pane fade show active" id="mainInfo" role="tabpanel" aria-labelledby="main-tab">
                <div class="form-group row">
                    <label for="input_name" class="col-sm-4 col-xl-3 col-form-label">Название</label>
                    <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                        <input required class="form-control" type="text" name="name" value="<?=($editMode) ? $_RESPONSE['edit']->getName() : ''?>" id="input_name">
                    </div>
                </div>

                <?php foreach($fields as $field):?>
                    <?php $this->getTemplate('guides','format_fields',array('field'=>$field, 'value'=>($editMode) ? $_RESPONSE['edit']->getValue($field['name']) : ''));?>
                <?php endforeach;?>
            </div>
        </div>
        <div class="form_buttons">
            <div class="row">
                <?php  $this->getTemplate('pages','langSwitcher',array()); ?>
                <div class="col-6">
                    <button class="btn btn-success saveOutpost">Сохранить</button>
                </div>
            </div>
        </div>

<!--Конец кода из guides -> add_item -->


<div id="sections">
    <?php if($editMode){
        $groups = [];
        $selectedValues = $this->getValue($_RESPONSE['edit'], 'groups_fields');
        $guideItems = $this->macros('guides','list_items',array($_RESPONSE['edit']->_guideFields['groups_fields']['fromId'], $selectedValues, true, 'ASC', 'id',true));


        foreach($guideItems['data'] as $field){
            $groups[$field->getValue('section')][] = $field;
        }

        ksort($groups);
      
        foreach($groups as $groupId=>$fields){
            $this->getTemplate('formgenerator', 'section', $fields);
        }
    }
    ?>
  
</div>

<button type="button" class="btn btn-primary add_section_row">Добавить шаг</button>
<div id="div_del"></div>
          </form>
</div>
    