<div class="ex_section" style="<?=($_RESPONSE) ? '' : 'display:none'?>">
    <div class="card card-outline card-primary mb-3 card_example">
        <div class="card-header">
            <div class="float-right">
                <button type="button" class="btn btn-primary" onclick="add_field_row(this)">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
                    Добавить поле
                </button>
                <button type="button" class="btn btn-danger del_section" onclick="del_section_row(this)" style="display:none;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-minus-circle"><circle cx="12" cy="12" r="10"></circle><line x1="8" y1="12" x2="16" y2="12"></line></svg>
                    Удалить шаг
                </button>
            </div>
            <h4 class="card-title"></h4>
        </div>
        <!-- /.card-header -->

        <div class="card-body">
            <?php if(!$_RESPONSE){ $_RESPONSE[] = [];}
          $guidesList = guides::lists(false, false);
          $guides=$guidesList['data'];
          ?>
            
            <?php foreach($_RESPONSE as $field):?>
            <? $row_id = $this->getValue($field, 'id', false, true);?>
                <div class="row form_row">
                    <div class="col-md-5">
                        <div class="form-group">
                            <label>Имя поля</label>
                            <input type="text" class="form-control" name="fields[name][<?=$row_id?>]" value="<?=$this->getValue($field, 'name', false, true)?>">
                        </div>
                        <div class="form-check mb-2 mr-sm-2">
                            <label class="form-check-label" >
                                <input class="form-check-input" type="checkbox" name="fields[required][<?=$row_id?>]" value="1" <?=$this->getValue($field, 'required', false, true) ? 'checked':''?>>
                                Обязательное поле
                            </label>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Тип поля</label>
                            
                            <?php 
                                $fieldTypes = [
                                "varchar"=>"Строка",
                                "textarea"=>"Многострочное поле",
                                "varcharru"=>"Строка (Кириллица)",
                                "phonenumber"=>"Номер телефона",
                                "passport"=>"Номер паспорта",
                                "snils"=>"СНИЛС",
                                "email"=>"E-mail",
                                "date"=>"Дата",
                                "datetime"=>"Дата и время",
                                "int"=>"Число",
                                "float"=>"Число с точкой",
                                "boolean"=>"Галочка",
                                "file"=>"Файл",
                                "filelist"=>"Набор файлов",
                                "list"=>"Список определенных значений",
                                "guide"=>"Список значений другого справочника",
                                "guide_ajax"=>"Ajax cписок значений другого справочника",
                                "guide_ajax_empty"=>"Ajax пустой cписок",
  
                                "module_time_reservation"=>"Модуль выбора времения для записи на прием"
                                ];

                                $selectedType = $this->getValue($field, 'type');
                            ?>
                            
                            <select name="fields[type][<?=$row_id?>]" class="need_form-control" onchange="typeselect(this)">
                                <?php foreach($fieldTypes as $fieldType=>$fieldTypeRu):?>
                                    <option <?=$this->optSel($fieldType, $selectedType)?> value="<?=$fieldType?>"><?=$fieldTypeRu?></option>
                                <?php endforeach;?>
                            </select>
                            
                            <div class="pt-2 extra_field_select" <?=(($selectedType=='guide') || ($selectedType=='guide_ajax') || ($selectedType=='guide_ajax_empty'))?'':'style="display:none"'?>>
                              <? $selectedType = $this->getValue($field, 'extra'); ?>
                              <label>Выберите справочник:</label>
                               <select class="need_form-control pt-5" onchange="extra_field_select(this)">
                                 <option value="">-</option>
                                  <?php foreach($guides as $guide):?>
                                    <option <?=$this->optSel($guide->getId(), $selectedType)?> value="<?=$guide->getId()?>"><?=$guide->getValue('descr')?></option>
                                <?php endforeach;?>
                              </select>
                            </div>
                         
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Ширина поля</label>
                            <?php $fieldWidth = [1=>'На всю ширину', 2=>'1/2', 3=>'1/3']; $selectedWidth = $this->getValue($field, 'width');?>
                            <select name="fields[width][<?=$row_id?>]">
                                <?php foreach($fieldWidth as $fieldWidthId=>$fieldWidthRu):?>
                                    <option <?=$this->optSel($fieldWidthId, $selectedWidth)?> value="<?=$fieldWidthId?>"><?=$fieldWidthRu?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-1 mt-4">
                        <input type="hidden" class="form-control row_section" name="fields[section][<?=$row_id?>]" value="<?=$this->getValue($field, 'section', false, true)?>">
                        <input type="hidden" class="form-control extra_field" name="fields[extra][<?=$row_id?>]" value="<?=$this->getValue($field, 'extra', false, true)?>">
                        <a href="#" onclick="del_field_row(this,<?=($row_id?$row_id:0)?>);">Удалить поле</a>
                    </div>
                </div>
            <?php endforeach;?>
        </div>
    </div>

</div>