<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>

<?php if($_RESPONSE['mode'] == 'lists'):?>
    <h1>Резервные копии</h1>
    <hr>
    <div><a href="/admin/monitoring/backup/add/files">Создать копию файлов</a> | <a href="/admin/monitoring/backup/add/db">Создать копию БД</a></div>
    <form action="/admin/monitoring/backup/cron" method="POST">
        <div class="form-group row">
            <label class="col-sm-4 col-xl-3 col-form-label">Время создания резервных копий</label>
            <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                <input type="text" name="hours" value="--" maxlength="2" style="width: 40px">:<input type="text" name="mins" value="--" maxlength="2" style="width: 40px">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-4 col-xl-3 col-form-label">Удалять копии старше чем (дней)</label>
            <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                <input type="text" name="days" value="---" maxlength="3" style="width: 40px">
            </div>
        </div>
        <button>ОК</button>
    </form>
    <br><br>
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th>Тип резервной копии</th>
                <th>Имя файла</th>
                <th>Размер</th>
                <th>Скачать</th>
                <th>Удалить</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($_RESPONSE['files'] as $file):?>
                <tr>
                    <td><?=$file['type']?></td>
                    <td><?=$file['full_name']?></td>
                    <td><?=$file['size']?> МБ</td>
                    <td><a href="/admin/monitoring/backup/download?backup=<?=$file['full_name']?>">Скачать</a></td>
                    <td><a href="/admin/monitoring/backup/del?backup=<?=$file['full_name']?>">Удалить</a></td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
<?php endif;?>