<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>
<?php if(isset($_GET['log'])):?>
    <?php $this->getTemplate('guides','list_items',$_RESPONSE);?>
<?php else:?>
    <h1>Мониторинг состояния веб-портала</h1>
    <hr>
    <h3>Ресурсы</h3>
    <table class="table table-striped table-sm">
        <tr><td style="width: 200px">Ресурс</td><td>Всего</td><td>Доступно / значение</td></tr>
        <tr><td>Нагрузка ЦП</td><td>(средняя нагрузка за 1, 5 и 15 минут)</td><td><?=implode(', ',$_RESPONSE['resources']['cpu'])?></td></tr>
        <tr><td>Оперативная память</td><td><?=$_RESPONSE['resources']['ram']['total']?></td><td><?=$_RESPONSE['resources']['ram']['free']?></td></tr>
        <?php if(isset($_RESPONSE['resources']['disks'])):?>
            <?php foreach($_RESPONSE['resources']['disks'] as $disk):?>
                <tr><td>Жесткий диск <?=$disk['name']?></td><td><?=$disk['total']?></td><td><?=$disk['free']?></td></tr>
            <?php endforeach;?>
        <?php endif;?>
    </table>

    <h3>Внешние сервисы</h3>
    <table class="table table-striped table-sm">
      <? $vneocheredi = file_get_contents("https://mfcdev.egov66.ru/services/vneocheredi.php?do=ping");?>
      <? $esia = file_get_contents("https://esia-portal1.test.gosuslugi.ru");?>
      <? $damask = file_get_contents("https://mfcdev.egov66.ru/services/damask.php?do=ping");?>
        <tr><td>ЕСИА</td><td><?=!empty($esia)?'Доступен':'Не доступен'?></td></tr>
        <tr><td>Внеочереди</td><td><?=($vneocheredi=='Ok'?'Доступен':'Не доступен')?></td></tr>
        <tr><td>Дамаск</td><td><?=($damask=='Ok'?'Доступен':'Не доступен')?></td></tr>
    </table>

    <hr>
    <p><a href="/admin/monitoring/backup">Управление резервными копиями</a></p>
<?php endif;?>