<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>
<section class="main-content">
    <div class="container">
        <div class="main-content__inner">
        <?php $this->getTemplateByFile('./templates/pages/parts/aside.phtml',[])?>
            <main class="main main-content__main">
                <div class="showcase">
                    <div class="showcase__content showcase__content--services">
                        <div>
                            <h1 class="showcase__title showcase__title--services">Дополнительные услуги</h1>
                        </div>
                        <div class="showcase__number showcase__number--services">

                        </div>
                    </div>
                </div>
                <div class="news">
                    <div class="our-services our-services--services">
                        <ul class="breadcrumbs our-services__breadcrumbs our-services__breadcrumbs--over">
                            <li class="breadcrumbs__item">Главная  </li>
                            <li class="breadcrumbs__item">Дополнительные услуги</li>
                        </ul>
                        <div class="our-services__content">

                            <div class="our-services__inner our-services__inner--over">
                                <div class="our-services__wrap-over">
                                    <ul class="our-services__over-list">
                                        <li class="our-services__over-item">
                                            <div class="our-services__over-row">
                                                <div class="our-services__over-col">
                                                    <p class="our-service__over-text">Широкий спектр сопутствующих услуг.</p>
                                                    <svg class="our-services__over-svg" ><use xlink:href="/sprite.svg#folder"></use></svg>
                                                </div>
                                                <div class="our-services__over-col">
                                                    <p class="our-service__over-text">Высококвалифицированные специалисты.</p>
                                                    <svg class="our-services__over-svg" ><use xlink:href="/sprite.svg#persons"></use></svg>
                                                </div>
                                                <div class="our-services__over-col">
                                                    <p class="our-service__over-text">Не нужно обращаться в посреднические организации.</p>
                                                    <svg class="our-services__over-svg" ><use xlink:href="/sprite.svg#over-check"></use></svg>
                                                </div>
                                                <div class="our-services__over-col">
                                                    <p class="our-service__over-text">Правовая поддержка.</p>
                                                    <svg class="our-services__over-svg" ><use xlink:href="/sprite.svg#over-low"></use></svg>
                                                </div>
                                                <div class="our-services__over-col">
                                                    <p class="our-service__over-text">Экономия времени для более важных дел.</p>
                                                    <svg class="our-services__over-svg" ><use xlink:href="/sprite.svg#over-clock"></use></svg>
                                                </div>
                                                <div class="our-services__over-col">
                                                    <p class="our-service__over-text">Гарантия честности и человеческого отношения.</p>
                                                    <svg class="our-services__over-svg" ><use xlink:href="/sprite.svg#over-deco"></use></svg>
                                                </div>
                                                <div class="our-services__over-col">
                                                    <p class="our-service__over-text">Индивидуальный подход к каждой ситуации.</p>
                                                    <svg class="our-services__over-svg" ><use xlink:href="/sprite.svg#over-body"></use></svg>
                                                </div>
                                                <div class="our-services__over-col">
                                                    <p class="our-service__over-text">Стоимость услуг рассчитана в соответствии с действующим законодательством.</p>
                                                    <svg class="our-services__over-svg" ><use xlink:href="/sprite.svg#over-price"></use></svg>
                                                </div>
                                                <div class="our-services__over-col">
                                                    <p class="our-service__over-text">Все услуги можно получить в одном месте. </p>
                                                    <svg class="our-services__over-svg" ><use xlink:href="/sprite.svg#over-loc"></use></svg>
                                                </div>

                                            </div>
                                        </li>
                                    </ul>
                                    <?php $this->getTemplateByFile('./templates/pages/parts/svgs.phtml', ['what'=>'extend_services'])?>
                                </div>
                                <form action="" class=" search-form our-services__search-form">
                                    <input class="search-form__input" type="text" placeholder="Введите название услуги">
                                    <button class="search-form__btn"><svg class="search-form__icon"><use xlink:href="/sprite.svg#input-search"></use></svg></button>
                                </form>

                                <div class="our-services__filter">
                                    <span class="our-services__name">Сортировать:<i class="fas fa-angle-down our-services__sort-icon"></i></span>
                                    <ul class="our-services__filter-list">
                                        <li class="our-services__filter-item our-services__filter-item--over">по городу<i class="fas fa-angle-down our-services__fas-icon"></i></li>
                                    </ul>
                                </div>

                                <?php if(!isset($_RESPONSE['page'])){ $services = $_RESPONSE;}
                                else{ $services = $this->macros('extend_services', 'lists');}?>

                                <div class="over">
                                    <h2 class="over__title">Услуги для физических лиц</h2>
                                    <ul class="over__list">
                                        <?php foreach($services['data']['phis'] as $service):?>
                                            <li class="over__item">
                                                <a href="/extend_services/view/<?=$this->getId($service)?>" class="over__link-item">
                                                    <div class="over__wrap-img">
                                                        <img src="<?=$this->macros('files', 'getFileURL', [$this->getValue($service, 'icon')])?>" alt="" class="over__item-image">
                                                    </div>
                                                    <p class="over__item-description"><?=$this->getName($service)?></p>
                                                </a>
                                            </li>
                                        <?php endforeach;?>
                                    </ul>
                                    <h2 class="over__title">Услуги для юридических лиц</h2>
                                    <ul class="over__list">
                                        <?php foreach($services['data']['legal'] as $service):?>
                                            <li class="over__item">
                                                <a href="/extend_services/view/<?=$this->getId($service)?>" class="over__link-item">
                                                    <div class="over__wrap-img">
                                                        <img src="<?=$this->macros('files', 'getFileURL', [$this->getValue($service, 'icon')])?>" alt="" class="over__item-image">
                                                    </div>
                                                    <p class="over__item-description"><?=$this->getName($service)?></p>
                                                </a>
                                            </li>
                                        <?php endforeach;?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
</section>