<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>

<section class="main-content">
    <div class="container">
        <div class="main-content__inner">
        <?php $this->getTemplateByFile('./templates/pages/parts/aside.phtml',[])?>
            <main class="main main-content__main">
                <div class="showcase">
                    <div class="showcase__content showcase__content--services">
                        <div>
                            <h1 class="showcase__title showcase__title--services">Дополнительные услуги</h1>
                        </div>
                        <div class="showcase__number showcase__number--services">
                            <?php $this->getTemplateByFile('./templates/pages/parts/svgs.phtml', ['what'=>'extend_services_item'])?>
                        </div>
                    </div>
                </div>
                <div class="news">
                    <div class="our-services">
                        <ul class="breadcrumbs our-services__breadcrumbs">
                            <li class="breadcrumbs__item">Главная  </li>
                            <li class="breadcrumbs__item">Дополнительные услуги</li>
                        </ul>

                        <?php if($innerServices = $this->getValue($_RESPONSE['source'],'inner_services')):?>
                            <div class="our-services__content">
                                <div class="our-services__inner our-services__inner--over">
                                    <ul class="our-services__list our-services__list--over">
                                        <?php foreach($innerServices as $innerService):?>
                                            <li>
                                                <a class="our-services__list-item our-services__list-item--over" href="/extend_services/view/<?=$this->getId($innerService)?>">
                                                    <svg class="our-services__list-type our-services__list-type--law">
                                                        <use xlink:href="/sprite.svg#service-law"></use>
                                                    </svg>
                                                    <div class="our-services__list-description">
                                                        <span><?=$this->getName($innerService)?></span>
                                                    </div>
                                                </a>
                                            </li>
                                        <?php endforeach;?>
                                    </ul>
                                </div>
                            </div>
                        <?php else:?>

                            <div class="our-services__content">
                                <div class="our-services__inner our-services__inner--over">
                                    <div class="our-services__banner-top">
                                        <?php if($images = $this->getValue($_RESPONSE['source'], 'images')):?>
                                            <div class="our-services__banner-item">
                                                <div class="newslider">
                                                    <?php foreach($images as $image):?>
                                                        <div class="our-services__banner-slide"><img src="<?=$this->macros('files','getFileURL',[$image])?>" /></div>
                                                    <?php endforeach;?>
                                                </div>
                                            </div>
                                        <?php endif;?>
                                        <div class="our-services__banner-item">
                                            <h2 class="our-services__banner-title"><?=$this->getName($_RESPONSE['source'])?></h2>
                                            <div class="our-services__banner-text">
                                                <?=$this->getValue($_RESPONSE['source'],'short_descr', false)?>
                                            </div>

                                            <?php $cities = $this->macros('offices','getCitiesFromOfficeList', [$this->getValue($_RESPONSE['source'], 'offices')]);?>

                                            <div class="user__form-item">
                                                <div class="user__form-select">
                                                    <i class="fas fa-angle-down user__fas-icon user__fas-icon--over"></i>
                                                    <select class="user__form-input user__form-input--over" name="city" id="">
                                                        <option value="0">Выберите город</option>
                                                        <?php foreach($cities as $city):?>
                                                            <option value="<?=$this->getId($city)?>"><?=$this->getName($city)?></option>
                                                        <?php endforeach;?>
                                                    </select>
                                                </div>
                                            </div>
                                            <?php $lots = $this->getValue($_RESPONSE['source'], 'lots');?>
                                            <div class="user__wrap-form-item user__wrap-form-item--over">
                                                <div class="user__form-item user__form-item--wrap">
                                                    <div class="user__form-item">
                                                        <div class="user__form-select">
                                                            <i class="fas fa-angle-down user__fas-icon user__fas-icon--over"></i>
                                                            <select class="user__form-input user__form-input--over" name="lot">
                                                                <option value="0">
                                                                    <?php if($lotsText = $this->getValue($_RESPONSE['source'], 'lots_text')):?>
                                                                        <?=$lotsText;?>
                                                                    <?php else:?>
                                                                        Выберите лот
                                                                    <?php endif;?>
                                                                </option>
                                                                <?php foreach($lots as $lot):?>
                                                                    <option data-price="<?=$this->getValue($lot, 'price')?>" value="<?=$this->getId($lot)?>"><?=$this->getName($lot)?></option>
                                                                <?php endforeach;?>
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="user__form-item user__form-item--wrap">
                                                    <div class="user__form-item">
                                                        <!-- <label class="user__form-label" for="">Адрес регистрации (пребывания), по которому будет осуществлён выезд Город*</label> -->
                                                        <div class="user__form-select">
                                                            <i class="fas fa-angle-down user__fas-icon user__fas-icon--over"></i>
                                                            <select class="user__form-input user__form-input--over" name="amount">
                                                                <option value="0">Количество</option>
                                                                <?php for($i = 1; $i <= 15; $i++):?>
                                                                    <option value="<?=$i?>"><?=$i?></option>
                                                                <?php endfor;?>
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <p class="our-services__banner-text">
                                                <span style="font-weight: bold;">Стоимость:</span>
                                                <span id="price">
                                                    Сперва выберите лот и количество
                                                </span>
                                            </p>
                                            <div class="">
                                                <button class="jobs__card-btn jobs__card-btn--over">Оплатить</button>
                                                <button class="jobs__card-btn jobs__card-btn--over">Оставить заявку</button>
                                            </div>

                                        </div>
                                    </div>
                                    <div class="user__tab">
                                        <?php
                                            $descr = $this->getValue($_RESPONSE['source'],'full_descr', false);
                                            $offices = $this->getValue($_RESPONSE['source'],'offices');
                                            $docs = $this->getValue($_RESPONSE['source'],'docs', false);
                                        ?>
                                        <ul class="user__tab-list">
                                            <?php /*if($descr):*/?>
                                                <li data-tab="tab-1" class="user__tab-item user__tab-item--active">Описание</li>
                                            <?php /*endif;*/?>
                                            <?php if($offices):?>
                                                <li data-tab="tab-2" class="user__tab-item">Список офисов</li>
                                            <?php endif;?>
                                            <?php if($docs):?>
                                                <li data-tab="tab-3" class="user__tab-item">Необходимые документы</li>
                                            <?php endif;?>
                                        </ul>
                                        <?php /*if($descr):*/?>
                                            <div class="user__tab-content tab-1">
                                                <?=$descr?>
                                            </div>
                                        <?php /*endif;*/?>
                                        <?php if($offices):?>
                                            <div class="user__tab-content tab-2 hide">
                                                <?php foreach($offices as $office):?>
                                                    <div>
                                                        <a href="/offices/view/<?=$this->getId($office)?>">
                                                            <?=$this->getName($office);?>
                                                        </a>
                                                    </div>
                                                <?php endforeach;?>
                                            </div>
                                        <?php endif;?>
                                        <?php if($docs):?>
                                            <div class="user__tab-content tab-3 hide">
                                                <?=$docs?>
                                            </div>
                                        <?php endif;?>
                                    </div>
                                    <?php if($other = $this->getValue($_RESPONSE['source'],'other_services')):?>
                                        <div class="over">
                                            <h2 class="over__title">Также заказывают</h2>
                                            <ul class="over-slider">
                                                <?php foreach($other as $otherService):?>
                                                    <li class="over__item">
                                                        <a href="/extend_services/view/<?=$this->getId($otherService)?>" class="over__link-item">
                                                            <div class="over__wrap-img">
                                                                <img src="<?=$this->macros('files','getFileURL', [$this->getValue($otherService, 'icon')])?>" alt="" class="over__item-image">
                                                            </div>
                                                            <p class="over__item-description"><?=$this->getName($otherService)?></p>
                                                        </a>
                                                    </li>
                                                <?php endforeach;?>
                                            </ul>
                                        </div>
                                    <?php endif;?>
                                </div>
                            </div>
                        <?php endif;?>
                    </div>
                </div>
            </main>
        </div>
    </div>
</section>