<?php
    $icons = ['clipboard','location','check','group','over-services','car','static','pub'];
?>

<aside class="sidebar main-content__sidebar" >
    <a href="#" class="sidebar__link">
        <a class="sidebar__link-logo sidebar__link-logo--top" href="/"><img class="sidebar__main-logo sidebar__main-logo--top"  src="<?=$this->getSetting('mfc_logo')?>" alt=""></a>
    </a>
    <ul class="sidebar__nav-list" data-aos="fade-up" data-aos-easing="linear" data-aos-duration="1500">
        <?php $leftMenu = $this->macros('menu', 'getMenu', ['left_menu']);?>
        <?php foreach($leftMenu as $i=>$menuItem):?>
            <li class="sidebar__nav-item">
                <a href="<?=$menuItem['href']?>" class="main-btn sidebar__nav-link <?=($i == 0) ? 'sidebar__nav-link--active':''?>">
                    <svg class="main-btn__icon <?=($i == 0) ? 'main-btn__icon--first' : ''?>"><use xlink:href="/sprite.svg#<?=@$icons[$i]?>"></use></svg>
                    <span class="main-btn__text <?=($i == 0) ? 'main-btn__text--first' : ''?>"><?=$menuItem['name']?></span>
                </a>
            </li>
        <?php endforeach;?>
    </ul>
</aside>