<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>

<?php if(isset($_RESPONSE['breadcrumbs'])):?>
<div class="breadcrumbs">
    <ul>
        <?php $totalCrumbs = (count($_RESPONSE['breadcrumbs'])-1);?>
        <?php foreach($_RESPONSE['breadcrumbs'] as $i=>$item):?>
            <li class="breadcrumb-item <?=($i == $totalCrumbs) ? 'last_crumb':''?>">
                <a href="<?=$item['url'];?>"><?=$item['name'];?></a>
            </li>
        <?endforeach;?>
    </ul>
</div>
<?php endif;?>