<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>

<div class="main_content_container">
    <h1>Удаление страницы</h1>

    <?php if(isset($_RESPONSE['confirm'])):?>
        <form action="/admin/pages/del/<?=$_RESPONSE['page']->getId()?>" id="form" method="POST">
            <h2 style="color:red">Вы действительно хотите удалить страницу "<?=$_RESPONSE['page']->getName()?>"?</h2>
            <p>Вместе с этой страницей будут удалены следующие элементы:</p>
            <?php if($_RESPONSE['object']):?>
                <p>Связанный объект "<?=$_RESPONSE['object']->getName()?>"</p>
                <input type="checkbox" name="dontDeleteObject" value="1">Не удалять объект
            <?php endif;?>

            <?php if($_RESPONSE['children']):?>
                <br><br>
                <p>Дочерние подстраницы и связанные с ними объекты:</p>
                <ul>
                    <?php foreach($_RESPONSE['children'] as $child):?>
                        <li><?=$child->getName()?></li>
                    <?php endforeach;?>
                </ul>
                <input type="checkbox" name="dontDeleteChildObjects" value="1">Не удалять объекты (однако страницы будут удалены)
            <?php endif;?>

            <input type="hidden" name="confirm" value="1">

            <div class="form_buttons">
                <div class="row">
                    <div class="col-6">
                        <button class="btn btn-danger">Удалить</button>
                    </div>
                </div>
            </div>
        </form>
    <?php else:?>

    <?php endif;?>

</div>
