<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>

<div class="main_content_container">
    <h1>Редактировать страницу</h1>

    <ul class="nav nav-tabs" id="guideTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link" id="main-tab" data-toggle="tab" href="#mainInfo" role="tab" aria-controls="main" aria-selected="true">Основные данные</a>
        </li>
        <li class="nav-item pageTab">
            <a class="nav-link active" id="page-tab" data-toggle="tab" href="#pageInfo" role="tab" aria-controls="page" aria-selected="false">Страница</a>
        </li>
    </ul>

    <form action="/admin/pages/edit/<?=$_RESPONSE['edit']->getId()?>" method="POST" id="form" enctype="multipart/form-data">
        <div class="tab-content" id="guideTabContent">
            <div class="tab-pane" id="mainInfo" role="tabpanel" aria-labelledby="main-tab">
                <?php if($_RESPONSE['source']):?>
                    <?php $fields = $_RESPONSE['source']->getValue('_guideFields');?>
                    <div class="form-group row">
                        <label for="input_name" class="col-sm-4 col-xl-3 col-form-label">Название</label>
                        <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                            <input required class="form-control" type="text" name="name" value="<?=$_RESPONSE['source']->getName()?>" id="input_name">
                        </div>
                    </div>

                    <?php $objData = array('guide'=>$_RESPONSE['objectGuide']->getId(), 'item'=>$_RESPONSE['source']->getId())?>
                    <?php foreach($fields as $field):?>
                        <?php $this->getTemplate('guides','format_fields', array('field'=>$field, 'value'=>$_RESPONSE['source']->getValue($field['name']),  'object'=>$objData))?>
                    <?php endforeach;?>
                <?php else:?>
                    <p>Эта страница не связана ни с каким объектом.</p>
                    <p>Чтобы связать страницу с объектом, выберите справочник, введите название объекта в поле "поиск объекта", и выберите нужный объект</p>
                    <div class="form-group row">
                        <label for="input_page_name" class="col-sm-4 col-xl-3 col-form-label">Справочник</label>
                        <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                            <select class="form-control" name="page[source_guide]">
                                <option value="0">[не выбран]</option>
                                <?php if($_RESPONSE['guides']):?>
                                    <?php foreach($_RESPONSE['guides'] as $guide):?>
                                        <option value="<?=$guide->getId()?>"><?=$guide->getValue('descr')?></option>
                                    <?php endforeach;?>
                                <?php endif;?>
                            </select>
                            <a data-toggle="modal-ajax" data-title="Добавить элемент в справочник" class="open-modal btn btn-outline-dark btn-sm addNewObject" href="#">Создать новый объект</a>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="input_page_name" class="col-sm-4 col-xl-3 col-form-label">Найти объект</label>
                        <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                            <input type="text" id="search_source" class="form-control" placeholder="поиск объекта">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="input_page_name" class="col-sm-4 col-xl-3 col-form-label">Подходящие объекты</label>
                        <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                            <select class="form-control" name="page[source_object]">
                                <option value="0">[не выбран]</option>
                            </select>
                        </div>
                    </div>


                <?php endif;?>
            </div>

            <div class="tab-pane fade show active" id="pageInfo" role="tabpanel" aria-labelledby="page-tab">
                <div id="pageWrapper">
                    <?php
                        $fields = $_RESPONSE['edit']->_guideFields;
                        $_RESPONSE['fromModule'] = 'pages';
                        $pageData = array('guide'=>$_RESPONSE['guide']->getId(), 'item'=>$_RESPONSE['edit']->getId());
                    ?>

                    <?php $this->getTemplate('pages','standard_page_fields',$_RESPONSE);?>

                    <?php foreach($fields as $field):?>
                        <?php $this->getTemplate('guides','format_fields', array('field'=>$field, 'value'=>$_RESPONSE['edit']->getValue($field['name']),'object'=>$pageData, 'is_page'=>1))?>
                    <?php endforeach;?>

                    <div class="form-group row">
                        <label for="input_is_index_page" class="col-sm-4 col-xl-3 col-form-label">Использовать как главную страницу сайта</label>
                        <div class="col-sm-8 col-md-8 col-lg-9 col-xl-9">
                            <input type="checkbox" name="page[is_index_page]" value="1" <?=($_RESPONSE['edit']->getValue('is_index_page')) ? 'checked':''?>>
                        </div>
                    </div>

                    <?php if(isset($_RESPONSE['extend']['data']) and count($_RESPONSE['extend']['data'])):?>
                        <h2>Дополнительные поля</h2>
                        <?php foreach($_RESPONSE['extend']['data'] as $additional_field):?>
                            <?php
                            $field = array(
                                'name'=>$additional_field->getName(),
                                'descr'=>$additional_field->getValue('descr'),
                                'type'=>$additional_field->getValue('type')
                            );
                            if($additional_field->getValue('guideAsTable')){ $field['guideAsTable'] = 1;}
                            if($additional_field->getValue('type') == 'list'){ $field['list'] = $additional_field->getValue('additional_data');}
                            if($additional_field->getValue('type') == 'guide'){ $field['fromId'] = $additional_field->getValue('additional_data');}
                            if($additional_field->getValue('multiple')){ $field['multiple'] = 1;}

                            $value = $additional_field->getValue('value');
                            ?>
                            <?php $this->getTemplate('guides','format_fields', array('field'=>$field, 'value'=>$value, 'object'=>['guide'=>'page_extend', 'item'=>$additional_field->getId()]))?>
                        <?php endforeach;?>
                    <?php endif;?>
                </div>
            </div>
        </div>

        <div class="form_buttons">

            <div class="row">
                <div class="col-auto">
                    <a id="watchOnSite" class="btn btn-outline-dark" target="_blank" href="/<?=$_RESPONSE['edit']->getValue('lang')?>/<?=$_RESPONSE['edit']->getValue('url')?>" title="Посмотреть страницу на сайте"><span data-feather="eye"></span></a>
                </div>
                <?php
                    $this->getTemplate('pages','langSwitcher',array('pageId'=>$_RESPONSE['edit']->getId(),'lang'=>$_RESPONSE['edit']->getValue('lang'),'fromModule'=>$_RESPONSE['edit']->getObjectClassName()));
                ?>

                <div class="col-auto">
                    <button class="btn btn-success saveOutpost">Сохранить</button>
                </div>
                <div class="col-auto">
                    <a class="btn btn-danger" href="/admin/pages/del/<?=$_RESPONSE['edit']->getId()?>">Удалить</a>
                </div>
            </div>
        </div>
    </form>
</div>