<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>
<?php
$limit = utils::getRowsLimit();
$page = isset($_GET['page']) ? $_GET['page'] : 1;
$allLangs = languages::lists(false);
?>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <span>
        Язык страниц:
        <?php foreach($allLangs as $langPrefix=>$lang):?>
            <a <?=($langPrefix == $_RESPONSE['lang']) ? 'id="currentLang"':''?> data-prefix="<?=$langPrefix?>" class="lang-switch" href="/admin/pages/lists/0/<?=$langPrefix?>"><?=$lang?></a>
        <?php endforeach;?>
    </span>
</div>

<div id="listOfPages">
    <?php if(isset($_RESPONSE['data']) and $_RESPONSE['data']):?>
        <ul class="root">
            <li>
                <a href="#" class="pageLink" data-id="0">[Корень]</a>
            </li>

            <?php foreach($_RESPONSE['data'] as $k=>$guideItem):?>
                <li>
                    <a href="#" class="expandSubPages" data-id="<?=$guideItem->getId()?>" title="Развернуть подстраницы">[+]</a>
                    <a data-id="<?=$guideItem->getId()?>" class="pageLink" href="#" data-url="/<?=$guideItem->getValue('url')?>"><?=$guideItem->getName()?></a>
                </li>
            <?php endforeach;?>
        </ul>
    <?php else:?>
        Нет страниц
    <?php endif;?>
</div>


