<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2 col-auto">Дополнительные поля для страниц</h1>

    <div class="col-auto">
        <a href="/admin/pages/add_field" class="btn btn-outline-dark"><span data-feather="plus-circle"></span> Добавить поле</a>
    </div>
</div>
<table class="table table-striped table-sm">
    <thead>
    <tr>
        <th>Название</th>
        <th>Системное название</th>
        <th>Принадлежит странице</th>
    </tr>
    </thead>
    <tbody>
    <?php if(isset($_RESPONSE['data']) and $_RESPONSE['data']):?>
        <?php foreach($_RESPONSE['data'] as $guideItem):?>
            <tr>
                <td><a href="/admin/pages/edit_field/<?=$guideItem->getId()?>"><?=$guideItem->getValue('descr')?></a></td>
                <td><?=$guideItem->getName()?></td>
                <td>
                    <?php if($pageName = $this->macros('pages','getById',array($guideItem->getValue('pageId'),array('name')))):?>
                        <a href="/admin/pages/edit/<?=$guideItem->getValue('pageId')?>"><?=$pageName?></a>
                    <?php else:?>
                        Не определно
                    <?php endif;?>
                </td>
            </tr>
        <?php endforeach;?>
    <?php else:?>
        <td></td><td>Нет данных</td>
    <?php endif;?>
    </tbody>
</table>