
                                        <div class="answer">
                                            <ul class="answer__list">
                                                <li class="answer__item">
                                                    <h4 class="answer__title">Пишите</h4>
                                                    <img src="/img/req1.svg" alt="" class="answer__img">
                                                    <p class="answer__text">Написать сообщение в МФЦ</p>
                                                    <a href="/feedback" class="answer__btn">Форма обратной связи</a>
                                                </li>
                                                <li class="answer__item">
                                                    <h4 class="answer__title">Звоните</h4>
                                                    <img src="/img/req2.svg" alt="" class="answer__img">
                                                    <p class="answer__text">Телефон для справки</p>
                                                    <a href="#" class="answer__btn">8&thinsp;(343)&thinsp;273-00-08</a>
                                                </li>
                                                <li class="answer__item">
                                                    <h4 class="answer__title">Приходите</h4>
                                                    <img src="/img/req3.svg" alt="" class="answer__img">
                                                    <p class="answer__text">Посмотреть режим работы офисов</p>
                                                    <a href="/offices" class="answer__btn">Выбрать офис</a>
                                                </li>
                                                <li class="answer__item">
                                                    <h4 class="answer__title">Официальное <br>обращение в МФЦ</h4>
                                                    <img src="/img/req4.svg" alt="" class="answer__img">
                                                    <p class="answer__text">Данное обрашение рассматривается<br> в рамках 59-ФЗ</p>
                                                    <a href="/lk/view/appeal_mfc" class="answer__btn">Обратиться</a>
                                                </li>
                                            </ul>
                                        </div>
                                    