<form action="" class="user__inner-form">
                                            <!-- <div>
                                                <label class="user__inner-text user__inner-text--input" for="input-agree"><input id="input-agree" type="checkbox">&nbsp; Я согласен с условиями выезда</label>
                                            </div><br><br> -->
                                            <div class="user__form-item">
                                                <label class="user__form-label" for="">Ответ направить</label>
                                                <div><input class="user__form-input" type="text" placeholder="На электронную почту"></div>
                                            </div>
                                            <div class="user__form-item">
                                                <label class="user__form-label" for="">ФИО<span style="color: red">*</span></label>
                                                <div><input class="user__form-input" type="text" placeholder="Иванов Иван Иванович"></div>
                                            </div>

                                            <div class="search__row-item">
                                                <label class="user__form-label" for="text-area">Текст обращения</label>
                                                <div>
                                                    <textarea class="search__form-input" name="" id="text-area" cols="30" rows="10" style="width: 100%;">    
                                                    </textarea>
                                                </div>
                                            </div>

                                            <div class="user__form-item">
                                                <label class="user__form-label" for="">Город<span style="color: red">*</span></label>
                                                <div><input class="user__form-input" type="text" placeholder=""></div>
                                            </div>
                                            <div class="user__form-item">
                                                <label class="user__form-label" for="">Улица<span style="color: red">*</span></label>
                                                <div><input class="user__form-input" type="text" placeholder=""></div>
                                            </div>
                                            <div class="user__wrap-form-item">
                                                <div class="user__form-item user__form-item--wrap">
                                                    <label class="user__form-label" for="">Дом<span style="color: red">*</span></label>
                                                    <div><input class="user__form-input user__form-input--small" type="text" placeholder="01.01.2000"></div>
                                                </div>
                                                <div class="user__form-item user__form-item--wrap">
                                                    <label class="user__form-label" for="">Корпус<span style="color: red">*</span></label>
                                                    <div><input class="user__form-input user__form-input--small" type="text" placeholder="123-456"></div>
                                                </div>
                                                <div class="user__form-item user__form-item--wrap">
                                                    <label class="user__form-label" for="">Квартира<span style="color: red">*</span></label>
                                                    <div><input class="user__form-input user__form-input--small" type="text" placeholder="123-456"></div>
                                                </div>
                                            </div>
                                            <div class="user__wrap-form-item">
                                                <div class="user__form-item user__form-item--wrap user__form-item--fluid">
                                                    <label class="user__form-label" for="">Номер телефона<span style="color: red">*</span></label>
                                                    <div><input class="user__form-input" type="text" placeholder="01.01.2000"></div>
                                                </div>
                                                <div class="user__form-item user__form-item--wrap user__form-item--fluid">
                                                    <label class="user__form-label" for="">Электронная почта<span style="color: red">*</span></label>
                                                    <div><input class="user__form-input" type="text" placeholder="123-456"></div>
                                                </div>
                                            </div>
                                            <div class="user__form-item">
                                                <label class="user__form-label" for="">Приложить файлы</label>
                                                <div class="user__wrap-form-item user__wrap-form-item--btn">
                                                    <input class="user__form-input" type="text" placeholder="">
                                                    <button class="user__inner-btn user__inner-btn--form user__inner-btn--m16">Загрузить</button>
                                                    <button class="user__inner-btn user__inner-btn--form">
                                                        <svg width="23" height="21" viewBox="0 0 23 21" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                            <path d="M21 5H17.83L16 3H9V5H15.12L16.95 7H21V19H5V9H3V19C3 20.1 3.9 21 5 21H21C22.1 21 23 20.1 23 19V7C23 5.9 22.1 5 21 5ZM8 13C8 15.76 10.24 18 13 18C15.76 18 18 15.76 18 13C18 10.24 15.76 8 13 8C10.24 8 8 10.24 8 13ZM13 10C14.65 10 16 11.35 16 13C16 14.65 14.65 16 13 16C11.35 16 10 14.65 10 13C10 11.35 11.35 10 13 10ZM5 8V5H8V3H5V0H3V3H0V5H3V8H5Z" fill="#E04E39"></path>
                                                        </svg>   
                                                    </button>
                                                </div>
                                            </div>
                                            <br>
                                            <div>
                                                <label class="user__inner-text user__inner-text--input" for="input-agree"><input id="input-agree" type="checkbox">&nbsp; Я соглашаюсь с правилами приема и рассмотрения обращений<br>&nbsp; &nbsp; в электронном виде в ГБУ СО «МФЦ»</label>
                                            </div>

                                            <div class="user__bottom-btn">
                                                <button class="user__inner-btn user__inner-btn--form user__inner-btn--bottom">Отправить</button>
                                            </div>
                                        </form>