<ul class="user__list">
                                    <li class="user__list-item">
                                        <div class="user__card">
                                            <h6 class="user__card-title">Контакты</h6>
                                            <p class="user__card-text">Телефон</p>
                                            <p class="user__card-strong">8 800 555 35 35</p>
                                            <p class="user__card-text">Электронная почта</p>
                                            <p class="user__card-strong">ivan@Ivanov.ru</p>
                                            <!-- <svg class="user__card-icon"><use xlink:href="sprite.svg#rotor"></use></svg> -->
                                            <a href="#">
                                                <img class="user__card-icon" src="/img/rotor.png" alt="">
                                            </a>
                                        </div>
                                        <div class="user__card">
                                            <h6 class="user__card-title">Документы</h6>
                                            <p class="user__card-text">Документ удостоверяющий личность</p>
                                            <p class="user__card-text">Тип документа</p>
                                            <p class="user__card-strong">Паспорт гражданина РФ</p>
                                            <p class="user__card-text">Серия и номер</p>
                                            <p class="user__card-strong">1234 123456</p>
                                            <p class="user__card-text">Место рождения</p>
                                            <p class="user__card-strong">г. Екатеринбург</p>
                                            <p class="user__card-text">Дата выдачи</p>
                                            <p class="user__card-strong">01.01.2000</p>
                                            <p class="user__card-text">Кем выдан</p>
                                            <p class="user__card-strong">ТП № 1 г. Екатеринбург</p>
                                            <p class="user__card-text">Код подразделения</p>
                                            <p class="user__card-strong">012-345</p>
                                        </div>
                                    </li>
                                    <li class="user__list-item">
                                        <div class="user__card user__card--fixed">
                                            <h6 class="user__card-title">СНИЛС</h6>
                                            <p class="user__card-text">123-456-789</p>
                                            <h6 class="user__card-title">ИНН</h6>
                                            <p class="user__card-strong">1234567891234</p>
                                            <h6 class="user__card-title">Водительское удостоверение</h6>
                                            <p class="user__card-text">Номер</p>
                                            <p class="user__card-strong">1234 123456 </p>
                                            <p class="user__card-text">Дата выдачи</p>
                                            <p class="user__card-strong">01.01.2000</p>
                                            <p class="user__card-text">Действительно до</p>
                                            <p class="user__card-strong">01.01.3000</p>
                                            <p class="user__card-text">Свидетельство о рождении</p>
                                            <p class="user__card-strong">01.01.3000</p>
                                            <p class="user__card-text">Полис ОМС</p>
                                            <p class="user__card-strong">1234567891234567</p>
                                            <p class="user__card-text">Заграничный паспорт</p>
                                            <p class="user__card-strong">Не заполнен</p>
                                            <p class="user__card-text">Военный билет</p>
                                            <p class="user__card-strong">АА 1234567, выдан 01.01.2000</p>
                                        </div>
                                    </li>
                                   
                                </ul>
<div class="user__bottom-btn edit_btn" style="display:none;">
  <a href="?agree" class="user__inner-btn user__inner-btn--form user__inner-btn--bottom">Сохранить</a>
</div>