<?
$reserves = lk::get_all_reserve();

?>
                                        <h2 class="user__inner-title user__inner-title--status">Найти запись</h2>
                                        <form action="" class="search__form search__form--status">
                                            <div class="search_row-item">
                                                <label class="search__form-label" for="number">Номер записи</label>
                                                <div>
                                                    <input class="search__form-input search__form-input--status" type="text" id="number">
                                                </div>
                                            </div>
                                                <button type="submit" class="search__form-btn search__form-btn--status ">Найти</button>
                                        </form>
                                        <h2 class="user__inner-title user__inner-title--status">Мои записи</h2>
                                        <div class="our-services__filter our-services__filter--status">
                                            <span class="our-services__name">Сортировать:<i class="fas fa-angle-down our-services__sort-icon"></i></span> 
                                            <ul class="our-services__filter-list">
                                                <li class="our-services__filter-item our-services__filter-item--jobs">По дате<i class="fas fa-angle-down our-services__fas-icon"></i></li>
                                            </ul>
                                        </div>
                                        <div class="jobs">
                                            <ul class="jobs__card-list">
                                              <? foreach($reserves as $reserve){?>
                                                <li class="jobs__card-item jobs__card-item--status" data-date="<?=$reserve['date_ru']?>" data-checksum="<?=$reserve['checksum']?>"  data-docs="<?=$reserve['docs_count']?>" data-val='<?=$reserve['json']?>'>
                                                    <a href="#" onclick="view_reservation(this); return false;">
                                                        <p class="jobs__card-description jobs__card-description--status"><span class="jobs__card-strong">Запись №: <?=$reserve['token']?></span></p>
                                                        <p class="jobs__card-description jobs__card-description--status">
                                                            <span class="jobs__card-strong">Дата:</span><span><?=$reserve['date_ru']?></span>&nbsp;&nbsp;
                                                            <span class="jobs__card-strong">Время:</span><span style="color: #E04E39;"><?=$reserve['time']?></span><br>
                                                            <span class="jobs__card-strong" style="display: inline-block; margin-top: 8px;">Услуга:</span><span style="color: #E04E39;"><?=$reserve['service']?></span>
                                                        </p>
                                                        <p class="jobs__card-description jobs__card-description--status"><span class="jobs__card-strong">Офис:</span> <?=$reserve['office_addr']?></p>
                                                    </a>
                                                    <div class="jobs__wrap-card-btn">
                                                        <button class="jobs__card-btn jobs__card-btn--status cancel-js" onclick="cancel_reservation(this); return false;">Отменить</button>
                                                        <button class="jobs__card-btn jobs__card-btn--status info-js" onclick="view_reservation(this); return false;">Подробнее</button>
                                                    </div>
                                                </li>
                                              <?}?>
                                                
                                            </ul>
                                        </div>
                                    