
                                        <h2 class="user__inner-title user__inner-title--status">Найти заявку</h2>
                                        <form action="" class="search__form search__form--status">
                                            <div class="search_row-item">
                                                <label class="search__form-label" for="number">Номер заявки</label>
                                                <div>
                                                    <input class="search__form-input search__form-input--status" type="text" id="number">
                                                </div>
                                            </div>
                                                <button type="submit" class="search__form-btn search__form-btn--status ">Отправить</button>
                                        </form>
                                        <h2 class="user__inner-title user__inner-title--status">Мои обращения</h2>
                                        <!-- <div class="our-services__filter our-services__filter--status">
                                            <span class="our-services__name">Сортировать:<i class="fas fa-angle-down our-services__sort-icon"></i></span> 
                                            <ul class="our-services__filter-list">
                                                <li class="our-services__filter-item our-services__filter-item--jobs">По статусу услуги<i class="fas fa-angle-down our-services__fas-icon"></i></li>
                                            </ul>
                                        </div> -->
                                        <div class="jobs">
                                            <ul class="jobs__card-list">
                                                <li class="jobs__card-item jobs__card-item--status">
                                                    <a href="">
                                                        <p class="jobs__card-description jobs__card-description--status"><span class="jobs__card-strong">Запись №: А21-12345/2020</span></p>
                                                        <br>
                                                        <p class="jobs__card-description jobs__card-description--date">
                                                            <span class="jobs__card-strong">Дата:</span><span>3 июня 2021</span>
                                                        </p>
                                                        <p class="jobs__card-description jobs__card-description--cancel">Необходима замена паспорта по причине утери </p>
                                                    </a>
                                                    <div class="jobs__wrap-card-btn">
                                                        <button class="jobs__card-btn jobs__card-btn--status">Подробнее</button>
                                                    </div>
                                                </li>
                                                <li class="jobs__card-item jobs__card-item--status">
                                                    <a href="">
                                                        <p class="jobs__card-description jobs__card-description--status"><span class="jobs__card-strong">Запись №: А21-12345/2020</span></p>
                                                        <br>
                                                        <p class="jobs__card-description jobs__card-description--date">
                                                            <span class="jobs__card-strong">Дата:</span><span>3 июня 2021</span>
                                                        </p>
                                                        <p class="jobs__card-description jobs__card-description--cancel">Необходима замена паспорта по причине утери </p>
                                                    </a>
                                                    <div class="jobs__wrap-card-btn">
                                                        <button class="jobs__card-btn jobs__card-btn--status">Подробнее</button>
                                                    </div>
                                                </li>
                                                <li class="jobs__card-item jobs__card-item--status">
                                                    <a href="">
                                                        <p class="jobs__card-description jobs__card-description--status"><span class="jobs__card-strong">Запись №: А21-12345/2020</span></p>
                                                        <br>
                                                        <p class="jobs__card-description jobs__card-description--date">
                                                            <span class="jobs__card-strong">Дата:</span><span>3 июня 2021</span>
                                                        </p>
                                                        <p class="jobs__card-description jobs__card-description--cancel">Необходима замена паспорта по причине утери </p>
                                                    </a>
                                                    <div class="jobs__wrap-card-btn">
                                                        <button class="jobs__card-btn jobs__card-btn--status">Подробнее</button>
                                                    </div>
                                                </li>
                                                <li class="jobs__card-item jobs__card-item--status">
                                                    <a href="">
                                                        <p class="jobs__card-description jobs__card-description--status"><span class="jobs__card-strong">Запись №: А21-12345/2020</span></p>
                                                        <br>
                                                        <p class="jobs__card-description jobs__card-description--date">
                                                            <span class="jobs__card-strong">Дата:</span><span>3 июня 2021</span>
                                                        </p>
                                                        <p class="jobs__card-description jobs__card-description--cancel">Необходима замена паспорта по причине утери </p>
                                                    </a>
                                                    <div class="jobs__wrap-card-btn">
                                                        <button class="jobs__card-btn jobs__card-btn--status">Подробнее</button>
                                                    </div>
                                                </li><li class="jobs__card-item jobs__card-item--status">
                                                    <a href="">
                                                        <p class="jobs__card-description jobs__card-description--status"><span class="jobs__card-strong">Запись №: А21-12345/2020</span></p>
                                                        <br>
                                                        <p class="jobs__card-description jobs__card-description--date">
                                                            <span class="jobs__card-strong">Дата:</span><span>3 июня 2021</span>
                                                        </p>
                                                        <p class="jobs__card-description jobs__card-description--cancel">Необходима замена паспорта по причине утери </p>
                                                    </a>
                                                    <div class="jobs__wrap-card-btn">
                                                        <button class="jobs__card-btn jobs__card-btn--status">Подробнее</button>
                                                    </div>
                                                </li>
                                            </ul>
                                        </div>
                                    