
                                        <h4 class="user__inner-title">Отзыв согласия на обработку <br> персональных данных</h4>    
                                        <form action="" class="user__inner-form">
                                            <p class="user__form-label">Способ получения ответа<span style="color: red">*</span></p>
                                            <div>
                                                <div>
                                                    <label class="sidebar__label-service sidebar__label-service--form">
                                                        <input type="checkbox" class="sidebar__input">
                                                        <span class="sidebar__check-style sidebar__check-style--form"></span>
                                                        <span>Электронная почта</span>
                                                    </label>
                                                </div>
                                                <div>
                                                    <label class="sidebar__label-service sidebar__label-service--form">
                                                        <input type="checkbox" class="sidebar__input">
                                                        <span class="sidebar__check-style sidebar__check-style--form"></span>
                                                        <span>Почтовая связь</span>
                                                    </label>
                                                </div>
                                                <div>
                                                    <label class="sidebar__label-service sidebar__label-service--form">
                                                        <input type="checkbox" checked="" class="sidebar__input">
                                                        <span class="sidebar__check-style sidebar__check-style--form"></span>
                                                        <span>Электронная почта и почтовая связь</span>
                                                    </label>
                                                </div>
                                            </div>

                                            <div class="user__form-item">
                                                <label class="user__form-label" for="">Электронная почта<span style="color: red">*</span></label>
                                                <div><input class="user__form-input" type="text" placeholder="ivan@ivanov.ru"></div>
                                            </div>
                                            <div class="user__form-item">
                                                <label class="user__form-label" for="">Город<span style="color: red">*</span></label>
                                                <div><input class="user__form-input" type="text" placeholder=""></div>
                                            </div>
                                            <div class="user__form-item">
                                                <label class="user__form-label" for="">Улица<span style="color: red">*</span></label>
                                                <div><input class="user__form-input" type="text" placeholder="01.01.2000"></div>
                                            </div>
                                            <div class="user__wrap-form-item">
                                                <div class="user__form-item user__form-item--wrap">
                                                    <label class="user__form-label" for="">Дом<span style="color: red">*</span></label>
                                                    <div><input class="user__form-input user__form-input--small" type="text" placeholder="01.01.2000"></div>
                                                </div>
                                                <div class="user__form-item user__form-item--wrap">
                                                    <label class="user__form-label" for="">Корпус<span style="color: red">*</span></label>
                                                    <div><input class="user__form-input user__form-input--small" type="text" placeholder="123-456"></div>
                                                </div>
                                                <div class="user__form-item user__form-item--wrap">
                                                    <label class="user__form-label" for="">Квартира<span style="color: red">*</span></label>
                                                    <div><input class="user__form-input user__form-input--small" type="text" placeholder="123-456"></div>
                                                </div>
                                            </div>
                                            <div class="user__bottom-btn user__bottom-btn--data">
                                                <button class="user__inner-btn user__inner-btn--form user__inner-btn--data">Отправить</button>
                                            </div>
                                        </form>
                                    