<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>

<div class="main_content_container">
    <h1>Добавить</h1>

    <form action="/admin/guides/add/" method="POST" id="form">
        <div class="main_content_container_wrap">
            <div class="row row_form">
                <div class="col-3">
                    <p class="form_label">Внутреннее название справочника</p>
                    <small>Системное название, может содержать только английские буквы и цифры</small>
                </div>
                <div class="col-9">
                    <div class="form_wrapper">
                        <input class="form_input" required="" type="text" name="name" id="name" value="">
                    </div>
                </div>
            </div>
            <div class="row row_form">
                <div class="col-3">
                    <p class="form_label">Описание</p>
                    <small>Человекочитаемое название справочника</small>
                </div>
                <div class="col-9">
                    <div class="form_wrapper">
                        <input required class="form_input" type="text" name="descr" value="">
                    </div>
                </div>
            </div>
            <div class="row row_form">
                <div class="col-3">
                    <p class="form_label">Создать модуль</p>
                    <small>Создание отдельного php-класса для работы с этой сущностью. Вы сможете прописывать ей собственные методы
                        и шаблоны, а также обращаться к ее методам через /entity_name/method_name</small>
                </div>
                <div class="col-9">
                    <div class="form_wrapper">
                        <input type="checkbox" name="is_module" value="1" style="display: block">
                    </div>
                </div>
            </div>
            <div class="row row_form">
                <div class="col-3">
                    <p class="form_label">Создавать страницы для объектов</p>
                    <small>Объекты будут автоматически получать страницу с url-адресом</small>
                </div>
                <div class="col-9">
                    <div class="form_wrapper">
                        <input type="checkbox" name="auto_page" value="1" style="display: block">
                    </div>
                </div>
            </div>
            <div class="row row_form">
                <div class="col-3">
                    <p class="form_label">Отображать в меню</p>
                    <small>Вывести ссылку в левое меню админки на список объектов этого справочника</small>
                </div>
                <div class="col-3">
                    <div class="form_wrapper">
                        <input type="checkbox" name="show_in_menu" value="1" style="display: block">
                    </div>
                </div>
                <div class="col-3">
                    <p class="form_label">Класс для значка</p>
                    <small>Этот класс будет применен к пункту меню, если включено отображение</small>
                </div>
                <div class="col-3">
                    <div class="form_wrapper">
                        <input class="form_input" type="text" name="icon_class" id="icon_class" value="">
                    </div>
                </div>
            </div>
            <hr>
            <h2>Поля данных</h2>
            <hr>
            <div id="fields">
                <div style="margin-bottom: 20px">
                    <div class="row">
                        <div class="col-3">
                            <p class="form_label">Название поля</p>
                            <small>Системное название, может содержать только английские буквы и цифры</small>
                        </div>
                        <div class="col-3">
                            <div class="form_wrapper">
                                <input class="form_input" type="text" value="name" disabled>
                            </div>
                        </div>
                        <div class="col-3">
                            <p class="form_label">Описание поля</p>
                        </div>
                        <div class="col-3">
                            <div class="form_wrapper">
                                <input class="form_input" type="text" value="Название" disabled>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-3">
                            <p class="form_label">Тип поля</p>
                        </div>
                        <div class="col-3">
                            <div class="form_wrapper">
                                <select disabled>
                                    <option selected>Строка</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <hr>
                </div>

                <div class="fieldWrp" style="margin-bottom: 20px" data-count="%id%">
                    <div class="row">
                        <div class="col-3">
                            <p class="form_label">Название поля</p>
                            <small>Системное название, может содержать только английские буквы и цифры</small>
                        </div>
                        <div class="col-3">
                            <div class="form_wrapper">
                                <input class="form_input" required="" type="text" name="field_name[%id%]" id="field_name" value="">
                            </div>
                        </div>
                        <div class="col-3">
                            <p class="form_label">Описание поля</p>
                        </div>
                        <div class="col-3">
                            <div class="form_wrapper">
                                <input class="form_input" required="" type="text" name="field_descr[%id%]" value="">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-3">
                            <p class="form_label">Тип поля</p>
                        </div>
                        <div class="col-3">
                            <div class="form_wrapper">
                                <select name="field_type[%id%]" required="">
                                    <option value="varchar">Строка</option>
                                    <option value="text">Текст</option>
                                    <option value="htmltext">HTML-Текст</option>
                                    <option value="date">Дата</option>
                                    <option value="datetime">Дата и время</option>
                                    <option value="int">Число</option>
                                    <option value="float">Число с точкой</option>
                                    <option value="boolean">Галочка</option>
                                    <option value="file">Файл</option>
                                    <option value="filelist">Набор файлов</option>
                                    <option value="list">Список определенных значений</option>
                                    <option value="guide">Список значений другого справочника</option>
                                    <option value="json">JSON</option>
                                </select>
                            </div>
                        </div>

                        <div class="col-3 selectGuide" style="display: none">
                            <p class="form_label">Выбрать справочник</p>
                        </div>
                        <div class="col-3 selectGuide" style="display: none;">
                            <select name="guide[%id%]">
                                <?php foreach($_RESPONSE['guides'] as $guide):?>
                                    <option value="<?=$guide->getId()?>"><?=$guide->getValue('descr')?></option>
                                <?php endforeach;?>
                            </select>
                            <p class="form_label"><input type="checkbox" name="guideAsTable[%id%]">Отображать как список</p>
                            <p class="form_label"><input type="checkbox" name="multiple[%id%]">Можно выбрать несколько значений</p>
                        </div>

                        <div class="col-3 selectListItems" style="display: none">
                            <p class="form_label">Заполнить список</p>
                        </div>
                        <div class="col-3 selectListItems" style="display: none;">
                            <p class="listItemWrp">
                                <input type="text" name="field_values[%id%][]" placeholder="введите значение">
                                <a href="#" class="delListItem">[удалить]</a>
                            </p>
                            <a class="btn_sky addAnotherListItem" href="#">Добавить еще значение</a>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-3">
                            <p class="form_label">Приоритет вывода</p>
                            <small>Порядок, в котором поле будет отображаться в форме</small>
                        </div>
                        <div class="col-3">
                            <div class="form_wrapper">
                                <input class="form_input" type="number" name="field_index[%id%]" value="0">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-3">
                            <p class="form_label">Отображать в таблице</p>
                            <small>Значение поля будет отображаться в таблице элементов</small>
                        </div>
                        <div class="col-3">
                            <div class="form_wrapper">
                                <input class="form_input" type="checkbox" name="field_table[%id%]" value="1">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-3">
                            <p class="form_label">Поле обязательно для заполнения</p>
                        </div>
                        <div class="col-3">
                            <div class="form_wrapper">
                                <input class="form_input" type="checkbox" name="field_required[%id%]" value="1">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-3">
                            <p class="form_label">Скрытое поле</p>
                            <small>Поле не будет отображаться на страницах добавления/редактирования</small>
                        </div>
                        <div class="col-3">
                            <div class="form_wrapper">
                                <input class="form_input" type="checkbox" name="field_hidden[%id%]" value="1">
                            </div>
                        </div>
                        <!--<div class="col-3">
                            <p class="form_label">Заблокировать поле</p>
                            <small>При редактировании справочника поле будет невозможно переименовать, изменить тип данных и т.п.</small>
                        </div>
                        <div class="col-3">
                            <div class="form_wrapper">
                                <input class="form_input" type="checkbox" name="field_locked[%id%]" value="1">
                            </div>
                        </div>-->
                    </div>

                    <a href="#" class="delField btn_sky">Удалить</a>
                    <hr>
                </div>
            </div>

            <a href="#" class="btn_sky" id="addfield">Добавить поле</a>
        </div>

        <div class="form_buttons">
            <div class="row">
                <div class="col-6">
                    <button class="btn btn-success">Сохранить</button>
                </div>
            </div>
        </div>
    </form>
</div>