<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>

<div class="main_content_container">
    <h1>Добавление <span id="itemName"></span></h1>

    <?php if($_RESPONSE['guide']->getValue('is_module')){ $form_action = '/admin/'.$_RESPONSE['guide']->getName().'/add/';}
    else { $form_action = "/admin/guides/add_item/".$_RESPONSE['guide']->getId();}
    ?>
    <ul class="nav nav-tabs" id="guideTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="main-tab" data-toggle="tab" href="#mainInfo" role="tab" aria-controls="main" aria-selected="true">Основные данные</a>
        </li>
        <li class="nav-item pageTab" style="<?=($_RESPONSE['guide']->getValue('auto_page')) ? '':'display:none;'?>">
            <a class="nav-link" id="page-tab" data-toggle="tab" href="#pageInfo" role="tab" aria-controls="page" aria-selected="false">Страница</a>
        </li>
    </ul>
    <form action="<?=$form_action?>" method="POST" id="form" enctype="multipart/form-data">
        <?php $fields = $_RESPONSE['fields'];?>

        <div class="tab-content" id="guideTabContent">
            <div class="tab-pane fade show active" id="mainInfo" role="tabpanel" aria-labelledby="main-tab">
                <div class="form-group row">
                    <label for="input_create_page" class="col-sm-4 col-xl-3 col-form-label">Создать страницу</label>
                    <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                        <input type="checkbox" name="create_page" id="input_create_page" value="1" <?=($_RESPONSE['guide']->getValue('auto_page')) ? 'checked':''?>>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="input_name" class="col-sm-4 col-xl-3 col-form-label">Название</label>
                    <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                        <input required class="form-control" type="text" name="name" value="" id="input_name">
                    </div>
                </div>

                <?php foreach($fields as $field):?>
                    <?php $this->getTemplate('guides','format_fields',array('field'=>$field));?>
                <?php endforeach;?>
            </div>
            <?php if(/*$_RESPONSE['guide']->getValue('is_module') and*/ $_RESPONSE['guide']->getName()!='pages'):?>
            <div class="tab-pane fade" id="pageInfo" role="tabpanel" aria-labelledby="page-tab">
                <div id="pageWrapper">
                    <?php $pageFields = $this->macros('pages','add',array());?>
                    <?php $this->getTemplate('pages','standard_page_fields',array()) ?>
                    <?php foreach($pageFields['fields'] as $pageField):?>
                        <?php $this->getTemplate('guides','format_fields', array('field'=>$pageField, 'value'=>''))?>
                    <?php endforeach;?>
                </div>
            </div>
            <?php endif;?>
        </div>
        <div class="form_buttons">
            <div class="row">
                <?php  $this->getTemplate('pages','langSwitcher',array()); ?>
                <div class="col-6">
                    <button class="btn btn-success saveOutpost">Сохранить</button>
                </div>
            </div>
        </div>
    </form>
</div>