<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>

<div class="main_content_container">
    <?php if($_RESPONSE['guide']->getValue('is_module')){ $form_action = '/admin/'.$_RESPONSE['guide']->getName().'/add/';}
    else { $form_action = "/admin/guides/add_item/".$_RESPONSE['guide']->getId();}
    ?>

    <form action="<?=$form_action?>" method="POST" id="form" enctype="multipart/form-data">
        <?php $fields = $_RESPONSE['fields'];?>

        <div class="form-group row">
            <label for="input_name" class="col-sm-4 col-xl-3 col-form-label">Название</label>
            <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                <input required class="form-control" type="text" name="name" value="" id="input_name">
            </div>
        </div>

        <?php foreach($fields as $field):?>
            <?php $this->getTemplate('guides','format_fields',array('field'=>$field));?>
        <?php endforeach;?>
    </form>
</div>