<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>

<div class="main_content_container">
    <h1>Удаление справочника</h1>

    <?php if(isset($_RESPONSE['confirm'])):?>
        <form class="no-ajax" action="/admin/guides/del/<?=$_RESPONSE['guide']->getId()?>" id="form" method="POST">
            <h2 style="color:red">Вы действительно хотите удалить справочник "<?=$_RESPONSE['guide']->getName()?>"?</h2>
            <?php if($_RESPONSE['guide']->getValue('is_module')):?>
                <h4 style="color:#fd7e14">
                    <strong>Данный справочник является модулем! Если у вас в коде есть обращения к этому модулю, то они станут выдавать ошибку!</strong>
                </h4>
            <?php endif;?>

            <p>Удаление справочника удалит все хранящиеся в нем элементы! (<?=$_RESPONSE['objectsNumber']?> штук)</p>

            <?php if($_RESPONSE['pagesList']):?>
                <br><br>
                <p>Вместе с этим справочником будут удалены связанные с его объектами страницы:</p>
                <ul>
                    <?php foreach($_RESPONSE['pagesList'] as $page):?>
                        <li><a href="/admin/pages/edit/<?=$page['id']?>" target="_blank"><?=$page['name']?></a></li>
                    <?php endforeach;?>
                </ul>
            <?php endif;?>

            <input type="hidden" name="confirm" value="1">

            <div class="form_buttons">
                <div class="row">
                    <div class="col-6">
                        <button class="btn btn-danger">Удалить</button>
                    </div>
                </div>
            </div>
        </form>
    <?php endif;?>

</div>
