<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>

<div class="main_content_container">
    <h1>Редактировать <span id="itemName">«<?=$_RESPONSE['edit']->getName()?>»</span></h1>

    <?php if($_RESPONSE['guide']->getValue('is_module')){ $form_action = '/admin/'.$_RESPONSE['guide']->getName().'/edit/'.$_RESPONSE['edit']->getId();}
    else { $form_action = "/admin/guides/edit_item/".$_RESPONSE['guide']->getId()."/".$_RESPONSE['edit']->getId();}

    ?>
    <ul class="nav nav-tabs" id="guideTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="main-tab" data-toggle="tab" href="#mainInfo" role="tab" aria-controls="main" aria-selected="true">Основные данные</a>
        </li>
        <li class="nav-item pageTab" <?=(!$_RESPONSE['appendedPage']) ? 'style="display:none"':''?>>
            <a class="nav-link" id="page-tab" data-toggle="tab" href="#pageInfo" role="tab" aria-controls="page" aria-selected="false">Страница</a>
        </li>
    </ul>
    <form action="<?=$form_action?>" method="POST" id="form" enctype="multipart/form-data">
        
        <?php $fields = $_RESPONSE['edit']->getValue('_guideFields');?>

        <div class="tab-content" id="guideTabContent">
            <div class="tab-pane fade show active" id="mainInfo" role="tabpanel" aria-labelledby="main-tab">

                <?php if(!$_RESPONSE['appendedPage']):?>
                    <div class="form-group row">
                        <label for="input_create_page" class="col-sm-4 col-xl-3 col-form-label">Создать страницу</label>
                        <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                            <input type="checkbox" name="create_page" id="input_create_page" value="1">
                        </div>
                    </div>
                <?php endif;?>

                <div class="form-group row">
                    <label for="input_name" class="col-sm-4 col-xl-3 col-form-label">Название</label>
                    <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                        <input required class="form-control" type="text" name="name" value="<?=$_RESPONSE['edit']->getName()?>" id="input_name">
                    </div>
                </div>

                <?php $objData = array('guide'=>$_RESPONSE['guide']->getId(), 'item'=>$_RESPONSE['edit']->getId())?>
                <?php foreach($fields as $field):?>
                    <?php $this->getTemplate('guides','format_fields', array('field'=>$field, 'value'=>$_RESPONSE['edit']->getValue($field['name']), 'object'=>$objData))?>
                <?php endforeach;?>
            </div>
            <?php if(/*$_RESPONSE['guide']->getValue('is_module') and*/ $_RESPONSE['guide']->getName()!='pages'):?>
                <div class="tab-pane fade" id="pageInfo" role="tabpanel" aria-labelledby="page-tab">
                    <div id="pageWrapper">
                        <?php $pageFields = $this->macros('pages','add',array());?>
                        <?php $this->getTemplate('pages','standard_page_fields',array('edit'=>$_RESPONSE['appendedPage'], 'fromModule'=>$_RESPONSE['edit']->getObjectClassName())) ?>

                        <?php if(isset($_RESPONSE['appendedPage']) and $_RESPONSE['appendedPage']){
                            $pageData = array('guide'=>$pageFields['guide']->getId(), 'item'=>$_RESPONSE['appendedPage']->getId());
                        }
                        else { $pageData = array();}
                        ?>
                        <?php foreach($pageFields['fields'] as $pageField):?>
                            <?php $value = ($pageData) ? $_RESPONSE['appendedPage']->getValue($pageField['name']) : '';?>
                            <?php $this->getTemplate('guides','format_fields', array('field'=>$pageField, 'value'=>$value, 'object'=>$pageData, 'is_page'=>1))?>
                        <?php endforeach;?>

                        <?php if(isset($_RESPONSE['extend']['data']) and count($_RESPONSE['extend']['data'])):?>
                            <h2>Дополнительные поля</h2>
                            <?php foreach($_RESPONSE['extend']['data'] as $additional_field):?>
                                <?php
                                $field = array(
                                    'name'=>$additional_field->getName(),
                                    'descr'=>$additional_field->getValue('descr'),
                                    'type'=>$additional_field->getValue('type')
                                );
                                if($additional_field->getValue('guideAsTable')){ $field['guideAsTable'] = 1;}
                                if($additional_field->getValue('type') == 'list'){ $field['list'] = $additional_field->getValue('additional_data');}
                                if($additional_field->getValue('type') == 'guide'){ $field['fromId'] = $additional_field->getValue('additional_data');}
                                if($additional_field->getValue('multiple')){ $field['multiple'] = 1;}

                                $value = $additional_field->getValue('value');
                                ?>
                                <?php $this->getTemplate('guides','format_fields', array('field'=>$field, 'value'=>$value))?>
                            <?php endforeach;?>
                        <?php endif;?>
                    </div>
                </div>
            <?php endif;?>
        </div>
        <div class="form_buttons">
            <div class="row">
                <?php if($_RESPONSE['appendedPage']):?>
                    <div class="col-auto">
                        <a id="watchOnSite" class="btn btn-outline-dark" target="_blank" href="/<?=$_RESPONSE['appendedPage']->getValue('lang')?>/<?=$_RESPONSE['appendedPage']->getValue('url')?>" title="Посмотреть страницу на сайте"><span data-feather="eye"></span></a>
                    </div>
                <?php endif;?>

                <?php
                    if($_RESPONSE['appendedPage']){
                        $this->getTemplate('pages','langSwitcher',array('pageId'=>$_RESPONSE['appendedPage']->getId(),'lang'=>$_RESPONSE['appendedPage']->getValue('lang'),'fromModule'=>$_RESPONSE['edit']->getObjectClassName()));
                    }
                    else{
                        $this->getTemplate('pages','langSwitcher',array('lang'=>$_RESPONSE['edit']->getValue('lang'),'fromModule'=>$_RESPONSE['edit']->getObjectClassName()));
                    }
                ?>

                <div class="col-auto">
                    <button class="btn btn-success saveOutpost">Сохранить</button>
                </div>
                <div class="col-auto">
                    <a class="btn btn-danger" href="/admin/guides/del_item/<?=$_RESPONSE['guide']->getId()?>/<?=$_RESPONSE['edit']->getId()?>">Удалить</a>
                </div>
            </div>
        </div>
    </form>
</div>