<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>

<div class="main_content_container">

    <?php if($_RESPONSE['guide']->getValue('is_module')){ $form_action = '/admin/'.$_RESPONSE['guide']->getName().'/edit/'.$_RESPONSE['edit']->getId();}
    else { $form_action = "/admin/guides/edit_item/".$_RESPONSE['guide']->getId()."/".$_RESPONSE['edit']->getId();}

    ?>
    <form action="<?=$form_action?>" data-guide="<?=$_RESPONSE['guide']->getId()?>" data-item="<?=$_RESPONSE['edit']->getId()?>" method="POST" id="form" enctype="multipart/form-data">

        <?php $fields = $_RESPONSE['edit']->getValue('_guideFields');?>

        <div class="form-group row">
            <label for="input_name" class="col-sm-4 col-xl-3 col-form-label">Название</label>
            <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                <input required class="form-control" type="text" name="name" value="<?=$_RESPONSE['edit']->getName()?>" id="input_name">
            </div>
        </div>

        <?php $objData = array('guide'=>$_RESPONSE['guide']->getId(), 'item'=>$_RESPONSE['edit']->getId())?>
        <?php foreach($fields as $field):?>
            <?php $this->getTemplate('guides','format_fields', array('field'=>$field, 'value'=>$_RESPONSE['edit']->getValue($field['name']), 'object'=>$objData))?>
        <?php endforeach;?>

    </form>
</div>