<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>
<?php
    $hideValues = array('password');
    $field = $_RESPONSE['field'];
    if(in_array($field['name'], $hideValues)){ $value = '';}
    else { $value = isset($_RESPONSE['value']) ? $_RESPONSE['value'] : '';}

    if(isset($field['required']) and $field['required']){
        $required = 'required'; $field['descr'] .= ' *';
    }
    else{ $required = '';}

    if(isset($_RESPONSE['is_page'])){ $field['name'] = 'page['.$field['name'].']';}

    $randomId = rand(1,99999);
?>
<?php if(!isset($field['hidden']) or isset($_RESPONSE['ignore_hidden'])):?>
<div class="form-group row">
    <label for="input_<?=$randomId?>_<?=$field['name']?>" class="col-sm-4 col-xl-3 col-form-label"><?=$field['descr']?></label>
    <div class="col-sm-8 col-md-8 col-lg-9 col-xl-9">
        <?php switch($field['type']){
            case 'int':{?>
                <input type="number" <?=$required?> class="form-control" step="1" name="<?=$field['name']?>" id="input_<?=$randomId?>_<?=$field['name']?>" value="<?=$value?>">
                <? break;}

            case 'float':{?>
                <input type="number" <?=$required?> class="form-control" step="any" name="<?=$field['name']?>" id="input_<?=$randomId?>_<?=$field['name']?>" value="<?=$value?>">
                <? break;}

            case 'varchar':{?>
                <input type="text" <?=$required?> class="form-control" name="<?=$field['name']?>" id="input_<?=$randomId?>_<?=$field['name']?>" value="<?=$value?>">
                <? break;}

            case 'json':{?>
                <textarea <?=$required?> class="form-control"  name="<?=$field['name']?>" id="input_<?=$randomId?>_<?=$field['name']?>"><?=($value) ? json_encode($value) : '[]'?></textarea>
                <? break;}

            case 'text':{?>
                <textarea <?=$required?> class="form-control" name="<?=$field['name']?>" id="input_<?=$randomId?>_<?=$field['name']?>"><?=$value?></textarea>
                <? break;}

            case 'htmltext':{?>
                <textarea <?=$required?> class="htmlTextArea form-control" name="<?=$field['name']?>" id="input_<?=$randomId?>_<?=$field['name']?>"><?=$value?></textarea>
                <? break;}

            case 'date':{?>
                <input <?=$required?> type="date" class="form-control" name="<?=$field['name']?>" id="input_<?=$randomId?>_<?=$field['name']?>" value="<?=$value?>">
                <? break;}

            case 'datetime':{?>
                <input <?=$required?> type="datetime-local" class="form-control" name="<?=$field['name']?>" id="input_<?=$randomId?>_<?=$field['name']?>" value="<?=str_replace(' ','T',$value)?>">
                <? break;}

            case 'boolean':{?>
                <input <?=$required?> type="checkbox" name="<?=$field['name']?>" value="1" id="input_<?=$randomId?>_<?=$field['name']?>" <?=($value) ? 'checked':''?>>
                <? break;}

            case 'file':{?>
                <input <?=$required?> type="file" name="<?=$field['name']?>" id="input_<?=$randomId?>_<?=$field['name']?>">
                <?php if($value and files::getById($value,array('id'))):?>
                    <span class="fileWrapper">
                        <?php $preview = (string)$this->macros('files','preview',array($value, 0, 100,'resize')); ?>
                        <?php if($preview!='/file-not-image.jpg'):?>
                            <a href="/files/download/<?=$value?>">
                                <img src="<?=$preview?>">
                            </a>
                        <?php else:?>
                            <a href="/files/download/<?=$value?>">Скачать файл</a>
                        <?php endif;?>
                        <a class="delFile" data-guide="<?=$_RESPONSE['object']['guide']?>" data-item="<?=$_RESPONSE['object']['item']?>" data-field="<?=$field['name']?>" data-id="<?=$value?>" title="Удалить файл" href="#"><span data-feather="x-circle"></span></a>
                    </span>
                <?php endif;?>
                <? break;}

            case 'filelist':{?>
                <input <?=$required?> type="file" multiple name="<?=$field['name']?>[]" id="input_<?=$randomId?>_<?=$field['name']?>">
                <?php if($value):?>
                    <div class="fileListWrapper" data-field="<?=$field['name']?>">
                        <?php foreach($value as $fileId):?>
                            <?php if($file = files::getById($fileId,array('id'))): ?>
                                <span class="fileWrapper" data-file-id="<?=$fileId?>">
                                    <?php $preview = (string)$this->macros('files','preview',array($fileId, 0, 100, 'resize')); ?>
                                    <?php if($preview!='/file-not-image.jpg'):?>
                                        <a href="/files/download/<?=$fileId?>">
                                            <img src="<?=$preview?>">
                                        </a>
                                    <?php else:?>
                                        <a href="/files/download/<?=$fileId?>">Скачать файл</a>
                                    <?php endif;?>
                                    <a class="delFile" data-guide="<?=$_RESPONSE['object']['guide']?>" data-item="<?=$_RESPONSE['object']['item']?>" data-field="<?=$field['name']?>" data-id="<?=$fileId?>" href="#"><span data-feather="x-circle"></span></a>
                                </span>
                            <?php endif;?>
                        <?php endforeach;?>
                    </div>
                <?php endif;?>
                <? break;}

            case 'list':{?>
                <select <?=$required?> name="<?=$field['name']?>" class="form-control" id="input_<?=$randomId?>_<?=$field['name']?>">
                    <?php if(isset($field['list'])):?>
                        <?php foreach($field['list'] as $item):?>
                            <option <?=$this->optSel($value, $item)?>><?=$item?></option>
                        <?php endforeach;?>
                    <?php endif;?>
                </select>
                <? break;}

            case 'guide':{?>
                <?php $selectedValues = ($value and $value != 'null') ? $value : array();?>
                <?php if(isset($field['guideAsTable'])):?>
                    <?php
                        $guideItems = $this->macros('guides','list_items',array($field['fromId'], $selectedValues, false, false, false, true));
                    ?>
                    <table class="table table-sm guideAsTable" data-field="<?=$field['name']?>">
                        <thead>
                        <tr>
                            <th>Название</th>
                            <?php foreach($guideItems['need_fields'] as $guideField):?>
                                <th><?=$guideField['descr']?></th>
                            <?php endforeach;?>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                            <?php if(isset($guideItems['data']) and $selectedValues and $guideItems['data']):?>
                                <?php foreach($guideItems['data'] as $guideItem):?>
                                    <tr data-id="<?=$guideItem->getId()?>">
                                        <td>
                                            <a class="edit_guide_item" data-field="<?=$field['name']?>" data-toggle="modal-ajax" data-title="Редактировать элемент справочника" data-what="edit_guide_item" href="/admin/guides/edit_item_modal/<?=$field['fromId']?>/<?=$guideItem->getId()?>/?tpl=1"><?=$guideItem->getName()?></a>
                                        </td>
                                        <?php foreach($guideItems['need_fields'] as $guideField):?>
                                            <?php $guideFieldValue = $guideItem->getValue($guideField['name']);?>

                                            <td>
                                                <?php if($guideField['type'] == 'file'):?>
                                                    <?php $preview = (string)$this->macros('files','preview',array($guideFieldValue, 50, 50,'crop')); ?>
                                                    <?php if($preview):?>
                                                        <a href="/files/download/<?=$guideFieldValue?>"><img width="50" height="50" src="<?=$preview?>"></a>
                                                    <?php else:?>
                                                        <a href="/files/download/<?=$guideFieldValue?>">Скачать файл</a>
                                                    <?php endif;?>
                                                <?php else:?>
                                                    <?=$guideFieldValue?>
                                                <?php endif;?>
                                            </td>
                                        <?php endforeach;?>

                                        <td class="td_del">
                                            <input style="display:none" type="checkbox" checked name="<?=$field['name']?>[]" value="<?=$guideItem->getId()?>">
                                            <a class="del_guide_item" title="Удалить" href="/admin/guides/del_item/<?=$field['fromId']?>/<?=$guideItem->getId()?>"><span data-feather="x-circle"></span></a>
                                        </td>
                                    </tr>
                                <?php endforeach;?>
                            <?php endif;?>
                        </tbody>
                    </table>
                    <a data-field="<?=$field['name']?>" data-toggle="modal-ajax" data-title="Добавить элемент в справочник" data-what="add_guide_item" class="open-modal btn btn-outline-dark btn-sm" href="/admin/guides/add_item_modal/<?=$field['fromId']?>/?tpl=1">Добавить</a>

                <?php else:?>
                    <?php $guideItems = $this->macros('guides','list_items',array($field['fromId'], false, false, 'DESC', 'id', true)); ?>
                    <select <?=$required?> <?=(isset($field['multiple'])) ? 'multiple' : ''?> name="<?=$field['name']?><?=(isset($field['multiple'])) ? '[]' : ''?>" class="form-control" id="input_<?=$randomId?>_<?=$field['name']?>">
                        <?php if(!isset($field['multiple'])):?>
                            <option value="0">Не выбрано</option>
                        <?php endif;?>
                        <?php foreach($guideItems['data'] as $guideItem):?>
                            <?php if(isset($field['multiple'])):?>
                                <option <?=(in_array($guideItem->getId(), $selectedValues)) ? 'selected':''?> value="<?=$guideItem->getId()?>"><?=$guideItem->getName()?></option>
                            <?php else:?>
                                <option <?=$this->optSel($guideItem->getId(), $selectedValues) ? 'selected':''?> value="<?=$guideItem->getId()?>"><?=$guideItem->getName()?></option>
                            <?php endif;?>
                        <?php endforeach;?>
                    </select>
                <?php endif;?>
            <? break;}
        }?>
    </div>
</div>
<?php endif;?>