<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>

<?php
$limit = utils::getRowsLimit();
$page = isset($_GET['page']) ? $_GET['page'] : 1;
?>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Список справочников и сущностей</h1><a href="/admin/guides/add" class="btn btn-outline-dark"><span data-feather="plus-circle"></span> Добавить справочник</a>
</div>
<table class="table table-striped table-sm numered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Название</th>
            <th>Системное название</th>
            <th>Является модулем</th>
            <th>Добавить наименование</th>
            <th>Просмотреть наименования</th>
            <th>Удалить</th>
        </tr>
    </thead>
    <tbody>
         <?php if($_RESPONSE):?>
            <?php foreach($_RESPONSE['data'] as $guide):?>
                <tr>
                    <td>
                        <?=$guide->getId()?>
                    </td>
                    <td>
                        <a href="/admin/guides/edit/<?=$guide->getId()?>"><?=$guide->getName()?></a>
                    </td>
                    <td>
                        <?=$guide->getValue('descr')?>
                    </td>
                    <td>
                        <?=($guide->getValue('is_module')) ? 'Да': 'Нет'?>
                    </td>
                    <td>
                        <a href="/admin/guides/add_item/<?=$guide->getId()?>">Добавить наименование</a>
                    </td>
                    <td>
                        <a href="/admin/guides/list_items/<?=$guide->getId()?>">Просмотреть наименования</a>
                    </td>
                    <td>
                        <a href="/admin/guides/del/<?=$guide->getId()?>"><span data-feather="x-circle"></span></a>
                    </td>
                </tr>
            <?php endforeach;?>
        <?php else:?>
            <tr>
                <td class="table_no_resources" colspan="6">
                    <p>Нет данных для отображения</p>
                </td>
            </tr>
        <?php endif;?>
    </tbody>
</table>
   

<div class="lists_table_footer">
    <div class="row">
        <div class="col-4">

        </div>
        <div class="col-8">
           <!-- --><?php /*$this->getTemplate('search','numpages',array('total'=>$_RESPONSE['total']))*/?>
        </div>
    </div>
</div>
