<html>
<head>
    <style>
        body {
            background: url(/admin/assets/sky.jpg) no-repeat;
            text-align: center;
            font-family: "trebuchet ms";
            background-size: cover;
        }

        section#auth {
            left: 50%;
            position: fixed;
            top: 50%;
            transform: translate(-50%, -50%);
            background: #6a98c3;
            padding: 0 20px;
            border: 1px solid #000;
            width: 300px;
        }

        .row {margin: 10px;}

        input[type="text"], input[type="password"] {width: 100%}
    </style>
</head>

<body class="auth_page">
<section id="auth">
    <div class="auth-wrapper">
        <div class="auth-wrapper-centered zoomer">

            <h1>Авторизация</h1>
            <form action="/admin/users/enter" method="post">
                <div class="main_content_container_wrap">
                    <div class="row form_row">
                        <div class="col-12">
                        </div>
                        <div class="col-12">
                            <div class="form_wrapper">
                                <input type="text" class="form_input" name="email" placeholder="E-mail или логин">
                            </div>
                        </div>
                    </div>
                    <div class="row form_row">
                        <div class="col-12">
                        </div>
                        <div class="col-12">
                            <div class="form_wrapper">
                                <input type="password" class="form_input" name="password" placeholder="Пароль" >
                            </div>
                        </div>
                    </div>
                    <div class="row form_row">
                        <div class="col-12"></div>
                        <div class="col-12">
                            <div class="form_wrapper">
                                <input type="checkbox" name="remember" value="1"> Запомнить меня
                            </div>
                        </div>
                    </div>
                    <div class="form_register_buttons">
                        <div class="row">
                            <div class="col-12 align-self-center">
                                <button class="btn_sky auth">Войти</button>
                            </div>
                        </div>
                    </div>

                    <input type="hidden" name="redirect" value="/admin">
                    <?php if(isset($_RESPONSE['info'])):?>
                        <?=$_RESPONSE['info']?>
                    <?php endif;?>
                </div>
            </form>
        </div>
    </div>
</section>
</body>
</html>

