<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Список пользователей</h1><a href="/admin/users/registrate" class="btn btn-outline-dark">Добавить пользователя</a>
</div>
<table class="table table-striped table-sm numered">
    <thead>
    <tr>
        <th>#</th>
        <th>Название</th>
    </tr>
    </thead>
    <tbody>
    <?php if($_RESPONSE['data']):?>
        <?php foreach($_RESPONSE['data'] as $k=>$user):?>
            <tr>
                <td><?=$user->getId()?></td>
                <td><a href="/admin/users/edit/<?=$user->getId()?>"><?=$user->getName()?></a></td>
            </tr>
        <?php endforeach;?>
    <?php else:?>
        <tr>
            <td></td><td>Нет данных для отображения</td>
        </tr>
    <?php endif;?>
    </tbody>
</table>

<?php $this->getTemplate('pages','numpages',array('total'=>$_RESPONSE['total']))?>