<? /** @var templater $this */ ?>
<? /** @var array $_RESPONSE */ ?>

<div class="main_content_container">
    <h1>Добавить пользователя</h1>

    <h3><?=(isset($_RESPONSE['info'])) ? $_RESPONSE['info'] : ''?></h3>

    <form action="/admin/users/registrate/1" method="POST" id="form" enctype="multipart/form-data">
        <div class="form-group row">
            <label for="login" class="col-sm-4 col-xl-3 col-form-label">Логин</label>
            <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                <input required class="form-control" type="text" name="name" value="" id="login">
            </div>
        </div>

        <div class="form-group row">
            <label for="email" class="col-sm-4 col-xl-3 col-form-label">E-mail</label>
            <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                <input required class="form-control" type="text" name="email" value="" id="email">
            </div>
        </div>

        <div class="form-group row">
            <label for="password" class="col-sm-4 col-xl-3 col-form-label">Пароль</label>
            <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                <input required class="form-control" type="password" name="password" value="" id="password">
            </div>
        </div>

        <div class="form-group row">
            <label for="password_confirm" class="col-sm-4 col-xl-3 col-form-label">Подтверждение пароля</label>
            <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                <input required class="form-control" type="password" name="password_confirm" value="" id="password_confirm">
            </div>
        </div>

        <div class="form-group row">
            <label for="user_type" class="col-sm-4 col-xl-3 col-form-label">Тип пользователя</label>
            <div class="col-sm-8 col-md-8 col-lg-6 col-xl-6">
                <select name="type" class="form-control" id="input_type">
                    <?php foreach($_RESPONSE['types'] as $type):?>
                        <option><?=$type?></option>
                    <?php endforeach;?>
                </select>
            </div>
        </div>

        <?php $fields = $_RESPONSE['fields'];?>
        <?php foreach($fields as $field):?>
            <?php $this->getTemplate('guides','format_fields', array('field'=>$field, 'value'=>''))?>
        <?php endforeach;?>

        <div class="form_buttons">
            <div class="row">
                <div class="col-6">
                    <button class="btn btn-primary saveOutpost">Сохранить</button>
                </div>
            </div>
        </div>
    </form>
</div>